# config file
tcl: "inputs/directives.tcl"
includes: "inputs/add_round_key/includes.txt"
orig_code: "inputs/add_round_key/orig_code.txt"
test_code: "inputs/add_round_key/test_code.txt"
top_function: "AddRoundKey"