// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2023.1_2/1049935 Production Release
//  HLS Date:       Sat Jun 10 10:53:51 PDT 2023
// 
//  Generated by:   ajh9498@hansolo.poly.edu
//  Generated date: Fri Feb 28 22:24:11 2025
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    filter_core_core_fsm
//  FSM Module
// ------------------------------------------------------------------


module filter_core_core_fsm (
  clk, rst_n, fsm_output, iir_for_1_C_0_tr0
);
  input clk;
  input rst_n;
  output [4:0] fsm_output;
  reg [4:0] fsm_output;
  input iir_for_1_C_0_tr0;


  // FSM State Type Declaration for filter_core_core_fsm_1
  parameter
    main_C_0 = 3'd0,
    main_C_1 = 3'd1,
    iir_for_1_C_0 = 3'd2,
    main_C_2 = 3'd3,
    main_C_3 = 3'd4;

  reg [2:0] state_var;
  reg [2:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : filter_core_core_fsm_1
    case (state_var)
      main_C_1 : begin
        fsm_output = 5'b00010;
        state_var_NS = iir_for_1_C_0;
      end
      iir_for_1_C_0 : begin
        fsm_output = 5'b00100;
        if ( iir_for_1_C_0_tr0 ) begin
          state_var_NS = main_C_2;
        end
        else begin
          state_var_NS = iir_for_1_C_0;
        end
      end
      main_C_2 : begin
        fsm_output = 5'b01000;
        state_var_NS = main_C_3;
      end
      main_C_3 : begin
        fsm_output = 5'b10000;
        state_var_NS = main_C_0;
      end
      // main_C_0
      default : begin
        fsm_output = 5'b00001;
        state_var_NS = main_C_1;
      end
    endcase
  end

  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      state_var <= main_C_0;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    filter_core
// ------------------------------------------------------------------


module filter_core (
  clk, rst_n, input_rsc_dat, input_triosy_lz, fir_output_rsc_dat, fir_output_triosy_lz,
      iir_output_rsc_dat, iir_output_triosy_lz
);
  input clk;
  input rst_n;
  input [31:0] input_rsc_dat;
  output input_triosy_lz;
  output [31:0] fir_output_rsc_dat;
  output fir_output_triosy_lz;
  output [31:0] iir_output_rsc_dat;
  output iir_output_triosy_lz;


  // Interconnect Declarations
  wire [31:0] input_rsci_idat;
  reg [31:0] fir_output_rsci_idat;
  reg iir_output_triosy_obj_ld;
  wire [4:0] fsm_output;
  wire iir_for_1_iir_for_1_nor_tmp;
  wire or_tmp_4;
  wire or_tmp_13;
  reg reg_fir_output_triosy_obj_ld_cse;
  wire iir_for_2_and_3_itm;
  wire [31:0] iir_for_1_mul_itm;
  wire signed [34:0] nl_iir_for_1_mul_itm;
  wire [31:0] z_out;
  wire [32:0] nl_z_out;
  wire [31:0] z_out_1;
  wire [32:0] nl_z_out_1;
  reg [31:0] fir_delay_lane_3_sva;
  reg [31:0] iir_input_delay_lane_2_sva;
  reg [31:0] iir_input_delay_lane_1_sva;
  reg [31:0] iir_input_delay_lane_3_sva;
  reg [31:0] iir_input_delay_lane_0_sva;
  reg [31:0] iir_output_delay_lane_2_sva;
  reg [31:0] iir_output_delay_lane_1_sva;
  reg [31:0] iir_output_delay_lane_3_sva;
  reg [31:0] iir_output_delay_lane_4_sva;
  reg [31:0] iir_feedforward_sva;
  reg [2:0] iir_for_1_i_2_0_sva;
  reg [31:0] iir_feedback_sva;
  reg [2:0] iir_for_2_i_2_0_sva;
  wire [2:0] iir_for_2_i_2_0_sva_2;
  wire [3:0] nl_iir_for_2_i_2_0_sva_2;
  wire [2:0] iir_for_1_i_2_0_sva_2;
  wire [3:0] nl_iir_for_1_i_2_0_sva_2;
  reg [31:0] reg_iir_output_rsci_idat_cse;

  wire[31:0] iir_for_1_mux_nl;
  wire[1:0] iir_for_1_mux_1_nl;
  wire[3:0] iir_for_1_acc_nl;
  wire[4:0] nl_iir_for_1_acc_nl;
  wire[3:0] iir_for_2_acc_nl;
  wire[4:0] nl_iir_for_2_acc_nl;
  wire[31:0] fir_for_1_mux_4_nl;
  wire[31:0] fir_for_1_acc_8_nl;
  wire[32:0] nl_fir_for_1_acc_8_nl;
  wire fir_for_1_or_1_nl;
  wire[29:0] fir_for_1_mux1h_3_nl;
  wire[29:0] fir_for_1_acc_9_nl;
  wire[30:0] nl_fir_for_1_acc_9_nl;
  wire fir_for_1_mux1h_4_nl;
  wire fir_for_1_fir_for_1_and_1_nl;
  wire fir_for_1_mux_5_nl;
  wire[31:0] fir_for_1_mux_6_nl;
  wire[31:0] fir_for_1_mux_7_nl;
  wire[31:0] fir_for_1_acc_10_nl;
  wire[32:0] nl_fir_for_1_acc_10_nl;
  wire[31:0] iir_for_2_mul_1_nl;
  wire signed [33:0] nl_iir_for_2_mul_1_nl;
  wire[31:0] iir_for_2_mux_1_nl;
  wire iir_for_2_or_2_nl;

  // Interconnect Declarations for Component Instantiations 
  ccs_in_v1 #(.rscid(32'sd1),
  .width(32'sd32)) input_rsci (
      .dat(input_rsc_dat),
      .idat(input_rsci_idat)
    );
  ccs_out_v1 #(.rscid(32'sd2),
  .width(32'sd32)) fir_output_rsci (
      .idat(fir_output_rsci_idat),
      .dat(fir_output_rsc_dat)
    );
  ccs_out_v1 #(.rscid(32'sd3),
  .width(32'sd32)) iir_output_rsci (
      .idat(reg_iir_output_rsci_idat_cse),
      .dat(iir_output_rsc_dat)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) input_triosy_obj (
      .ld(reg_fir_output_triosy_obj_ld_cse),
      .lz(input_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) fir_output_triosy_obj (
      .ld(reg_fir_output_triosy_obj_ld_cse),
      .lz(fir_output_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) iir_output_triosy_obj (
      .ld(iir_output_triosy_obj_ld),
      .lz(iir_output_triosy_lz)
    );
  filter_core_core_fsm filter_core_core_fsm_inst (
      .clk(clk),
      .rst_n(rst_n),
      .fsm_output(fsm_output),
      .iir_for_1_C_0_tr0(iir_for_1_iir_for_1_nor_tmp)
    );
  assign iir_for_2_and_3_itm = (iir_for_2_i_2_0_sva==3'b010);
  assign iir_for_1_mux_nl = MUX_v_32_5_2(fir_delay_lane_3_sva, iir_input_delay_lane_0_sva,
      iir_input_delay_lane_1_sva, iir_input_delay_lane_2_sva, iir_input_delay_lane_3_sva,
      iir_for_1_i_2_0_sva);
  assign iir_for_1_mux_1_nl = MUX_v_2_5_2(2'b01, 2'b10, 2'b11, 2'b10, 2'b01, iir_for_1_i_2_0_sva);
  assign nl_iir_for_1_mul_itm = $signed(iir_for_1_mux_nl) * $signed(conv_u2s_2_3(iir_for_1_mux_1_nl));
  assign iir_for_1_mul_itm = nl_iir_for_1_mul_itm[31:0];
  assign nl_iir_for_2_i_2_0_sva_2 = iir_for_2_i_2_0_sva + 3'b001;
  assign iir_for_2_i_2_0_sva_2 = nl_iir_for_2_i_2_0_sva_2[2:0];
  assign nl_iir_for_1_i_2_0_sva_2 = iir_for_1_i_2_0_sva + 3'b001;
  assign iir_for_1_i_2_0_sva_2 = nl_iir_for_1_i_2_0_sva_2[2:0];
  assign nl_iir_for_1_acc_nl = conv_u2s_3_4(iir_for_1_i_2_0_sva_2) + 4'b1011;
  assign iir_for_1_acc_nl = nl_iir_for_1_acc_nl[3:0];
  assign nl_iir_for_2_acc_nl = conv_u2s_3_4(iir_for_2_i_2_0_sva_2) + 4'b1011;
  assign iir_for_2_acc_nl = nl_iir_for_2_acc_nl[3:0];
  assign iir_for_1_iir_for_1_nor_tmp = ~((readslicef_4_1_3(iir_for_1_acc_nl)) | (readslicef_4_1_3(iir_for_2_acc_nl)));
  assign or_tmp_4 = ~((fsm_output[2]) & iir_for_1_iir_for_1_nor_tmp);
  assign or_tmp_13 = iir_for_1_iir_for_1_nor_tmp & (fsm_output[2]);
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      fir_output_rsci_idat <= 32'b00000000000000000000000000000000;
    end
    else if ( fsm_output[0] ) begin
      fir_output_rsci_idat <= z_out_1;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      reg_iir_output_rsci_idat_cse <= 32'b00000000000000000000000000000000;
    end
    else if ( fsm_output[3] ) begin
      reg_iir_output_rsci_idat_cse <= z_out;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_1_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_4 ) begin
      iir_output_delay_lane_1_sva <= reg_iir_output_rsci_idat_cse;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_2_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_4 ) begin
      iir_output_delay_lane_2_sva <= iir_output_delay_lane_1_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_3_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_4 ) begin
      iir_output_delay_lane_3_sva <= iir_output_delay_lane_2_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_4_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_4 ) begin
      iir_output_delay_lane_4_sva <= iir_output_delay_lane_3_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_input_delay_lane_0_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_4 ) begin
      iir_input_delay_lane_0_sva <= fir_delay_lane_3_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_input_delay_lane_1_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_4 ) begin
      iir_input_delay_lane_1_sva <= iir_input_delay_lane_0_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_input_delay_lane_2_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_4 ) begin
      iir_input_delay_lane_2_sva <= iir_input_delay_lane_1_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_input_delay_lane_3_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_4 ) begin
      iir_input_delay_lane_3_sva <= iir_input_delay_lane_2_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_triosy_obj_ld <= 1'b0;
      reg_fir_output_triosy_obj_ld_cse <= 1'b0;
      iir_for_2_i_2_0_sva <= 3'b000;
      iir_feedback_sva <= 32'b00000000000000000000000000000000;
      iir_for_1_i_2_0_sva <= 3'b000;
      iir_feedforward_sva <= 32'b00000000000000000000000000000000;
    end
    else begin
      iir_output_triosy_obj_ld <= fsm_output[3];
      reg_fir_output_triosy_obj_ld_cse <= or_tmp_13;
      iir_for_2_i_2_0_sva <= MUX_v_3_2_2(3'b000, iir_for_2_i_2_0_sva_2, (fsm_output[2]));
      iir_feedback_sva <= MUX_v_32_2_2(32'b00000000000000000000000000000000, z_out_1,
          (fsm_output[2]));
      iir_for_1_i_2_0_sva <= MUX_v_3_2_2(3'b000, iir_for_1_i_2_0_sva_2, (fsm_output[2]));
      iir_feedforward_sva <= MUX_v_32_2_2(32'b00000000000000000000000000000000, z_out,
          (fsm_output[2]));
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      fir_delay_lane_3_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( (fsm_output[0]) | or_tmp_13 ) begin
      fir_delay_lane_3_sva <= MUX_v_32_2_2(input_rsci_idat, iir_input_delay_lane_2_sva,
          or_tmp_13);
    end
  end
  assign nl_fir_for_1_acc_8_nl = fir_delay_lane_3_sva + ({(iir_input_delay_lane_0_sva[30:0])
      , 1'b1});
  assign fir_for_1_acc_8_nl = nl_fir_for_1_acc_8_nl[31:0];
  assign fir_for_1_or_1_nl = (fsm_output[3:2]!=2'b00);
  assign fir_for_1_mux_4_nl = MUX_v_32_2_2(fir_for_1_acc_8_nl, iir_feedforward_sva,
      fir_for_1_or_1_nl);
  assign nl_fir_for_1_acc_9_nl = (iir_input_delay_lane_2_sva[30:1]) + (iir_input_delay_lane_1_sva[29:0]);
  assign fir_for_1_acc_9_nl = nl_fir_for_1_acc_9_nl[29:0];
  assign fir_for_1_mux1h_3_nl = MUX1HOT_v_30_3_2(fir_for_1_acc_9_nl, (iir_for_1_mul_itm[31:2]),
      (iir_feedback_sva[31:2]), {(fsm_output[0]) , (fsm_output[2]) , (fsm_output[3])});
  assign fir_for_1_mux1h_4_nl = MUX1HOT_s_1_3_2((iir_input_delay_lane_2_sva[0]),
      (iir_for_1_mul_itm[1]), (iir_feedback_sva[1]), {(fsm_output[0]) , (fsm_output[2])
      , (fsm_output[3])});
  assign fir_for_1_mux_5_nl = MUX_s_1_2_2((iir_for_1_mul_itm[0]), (iir_feedback_sva[0]),
      fsm_output[3]);
  assign fir_for_1_fir_for_1_and_1_nl = fir_for_1_mux_5_nl & (~ (fsm_output[0]));
  assign nl_z_out = fir_for_1_mux_4_nl + ({fir_for_1_mux1h_3_nl , fir_for_1_mux1h_4_nl
      , fir_for_1_fir_for_1_and_1_nl});
  assign z_out = nl_z_out[31:0];
  assign fir_for_1_mux_6_nl = MUX_v_32_2_2(z_out, iir_feedback_sva, fsm_output[2]);
  assign nl_fir_for_1_acc_10_nl = input_rsci_idat + (~ iir_input_delay_lane_1_sva);
  assign fir_for_1_acc_10_nl = nl_fir_for_1_acc_10_nl[31:0];
  assign iir_for_2_mux_1_nl = MUX_v_32_5_2(reg_iir_output_rsci_idat_cse, iir_output_delay_lane_1_sva,
      iir_output_delay_lane_2_sva, iir_output_delay_lane_3_sva, iir_output_delay_lane_4_sva,
      iir_for_2_i_2_0_sva);
  assign iir_for_2_or_2_nl = (~((~((iir_for_2_i_2_0_sva!=3'b000))) | ((iir_for_2_i_2_0_sva==3'b011))
      | ((iir_for_2_i_2_0_sva==3'b100)))) | iir_for_2_and_3_itm;
  assign nl_iir_for_2_mul_1_nl = $signed(iir_for_2_mux_1_nl) * $signed(({iir_for_2_and_3_itm
      , iir_for_2_or_2_nl}));
  assign iir_for_2_mul_1_nl = nl_iir_for_2_mul_1_nl[31:0];
  assign fir_for_1_mux_7_nl = MUX_v_32_2_2(fir_for_1_acc_10_nl, iir_for_2_mul_1_nl,
      fsm_output[2]);
  assign nl_z_out_1 = fir_for_1_mux_6_nl + fir_for_1_mux_7_nl;
  assign z_out_1 = nl_z_out_1[31:0];

  function automatic  MUX1HOT_s_1_3_2;
    input  input_2;
    input  input_1;
    input  input_0;
    input [2:0] sel;
    reg  result;
  begin
    result = input_0 & sel[0];
    result = result | (input_1 & sel[1]);
    result = result | (input_2 & sel[2]);
    MUX1HOT_s_1_3_2 = result;
  end
  endfunction


  function automatic [29:0] MUX1HOT_v_30_3_2;
    input [29:0] input_2;
    input [29:0] input_1;
    input [29:0] input_0;
    input [2:0] sel;
    reg [29:0] result;
  begin
    result = input_0 & {30{sel[0]}};
    result = result | (input_1 & {30{sel[1]}});
    result = result | (input_2 & {30{sel[2]}});
    MUX1HOT_v_30_3_2 = result;
  end
  endfunction


  function automatic  MUX_s_1_2_2;
    input  input_0;
    input  input_1;
    input  sel;
    reg  result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_s_1_2_2 = result;
  end
  endfunction


  function automatic [1:0] MUX_v_2_5_2;
    input [1:0] input_0;
    input [1:0] input_1;
    input [1:0] input_2;
    input [1:0] input_3;
    input [1:0] input_4;
    input [2:0] sel;
    reg [1:0] result;
  begin
    case (sel)
      3'b000 : begin
        result = input_0;
      end
      3'b001 : begin
        result = input_1;
      end
      3'b010 : begin
        result = input_2;
      end
      3'b011 : begin
        result = input_3;
      end
      default : begin
        result = input_4;
      end
    endcase
    MUX_v_2_5_2 = result;
  end
  endfunction


  function automatic [31:0] MUX_v_32_2_2;
    input [31:0] input_0;
    input [31:0] input_1;
    input  sel;
    reg [31:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_32_2_2 = result;
  end
  endfunction


  function automatic [31:0] MUX_v_32_5_2;
    input [31:0] input_0;
    input [31:0] input_1;
    input [31:0] input_2;
    input [31:0] input_3;
    input [31:0] input_4;
    input [2:0] sel;
    reg [31:0] result;
  begin
    case (sel)
      3'b000 : begin
        result = input_0;
      end
      3'b001 : begin
        result = input_1;
      end
      3'b010 : begin
        result = input_2;
      end
      3'b011 : begin
        result = input_3;
      end
      default : begin
        result = input_4;
      end
    endcase
    MUX_v_32_5_2 = result;
  end
  endfunction


  function automatic [2:0] MUX_v_3_2_2;
    input [2:0] input_0;
    input [2:0] input_1;
    input  sel;
    reg [2:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_3_2_2 = result;
  end
  endfunction


  function automatic [0:0] readslicef_4_1_3;
    input [3:0] vector;
    reg [3:0] tmp;
  begin
    tmp = vector >> 3;
    readslicef_4_1_3 = tmp[0:0];
  end
  endfunction


  function automatic [2:0] conv_u2s_2_3 ;
    input [1:0]  vector ;
  begin
    conv_u2s_2_3 =  {1'b0, vector};
  end
  endfunction


  function automatic [3:0] conv_u2s_3_4 ;
    input [2:0]  vector ;
  begin
    conv_u2s_3_4 =  {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    filter
// ------------------------------------------------------------------


module filter (
  clk, rst_n, input_rsc_dat, input_triosy_lz, fir_output_rsc_dat, fir_output_triosy_lz,
      iir_output_rsc_dat, iir_output_triosy_lz
);
  input clk;
  input rst_n;
  input [31:0] input_rsc_dat;
  output input_triosy_lz;
  output [31:0] fir_output_rsc_dat;
  output fir_output_triosy_lz;
  output [31:0] iir_output_rsc_dat;
  output iir_output_triosy_lz;



  // Interconnect Declarations for Component Instantiations 
  filter_core filter_core_inst (
      .clk(clk),
      .rst_n(rst_n),
      .input_rsc_dat(input_rsc_dat),
      .input_triosy_lz(input_triosy_lz),
      .fir_output_rsc_dat(fir_output_rsc_dat),
      .fir_output_triosy_lz(fir_output_triosy_lz),
      .iir_output_rsc_dat(iir_output_rsc_dat),
      .iir_output_triosy_lz(iir_output_triosy_lz)
    );
endmodule



