
//------> /eda/mentor/Siemens_EDA/Catapult_Synthesis_2023.1_2/Mgc_home/pkgs/siflibs/ccs_in_v1.v 
//------------------------------------------------------------------------------
// Catapult Synthesis - Sample I/O Port Library
//
// Copyright (c) 2003-2017 Mentor Graphics Corp.
//       All Rights Reserved
//
// This document may be used and distributed without restriction provided that
// this copyright statement is not removed from the file and that any derivative
// work contains this copyright notice.
//
// The design information contained in this file is intended to be an example
// of the functionality which the end user may study in preparation for creating
// their own custom interfaces. This design does not necessarily present a 
// complete implementation of the named protocol or standard.
//
//------------------------------------------------------------------------------


module ccs_in_v1 (idat, dat);

  parameter integer rscid = 1;
  parameter integer width = 8;

  output [width-1:0] idat;
  input  [width-1:0] dat;

  wire   [width-1:0] idat;

  assign idat = dat;

endmodule


//------> /eda/mentor/Siemens_EDA/Catapult_Synthesis_2023.1_2/Mgc_home/pkgs/siflibs/ccs_out_v1.v 
//------------------------------------------------------------------------------
// Catapult Synthesis - Sample I/O Port Library
//
// Copyright (c) 2003-2015 Mentor Graphics Corp.
//       All Rights Reserved
//
// This document may be used and distributed without restriction provided that
// this copyright statement is not removed from the file and that any derivative
// work contains this copyright notice.
//
// The design information contained in this file is intended to be an example
// of the functionality which the end user may study in preparation for creating
// their own custom interfaces. This design does not necessarily present a 
// complete implementation of the named protocol or standard.
//
//------------------------------------------------------------------------------

module ccs_out_v1 (dat, idat);

  parameter integer rscid = 1;
  parameter integer width = 8;

  output   [width-1:0] dat;
  input    [width-1:0] idat;

  wire     [width-1:0] dat;

  assign dat = idat;

endmodule




//------> /eda/mentor/Siemens_EDA/Catapult_Synthesis_2023.1_2/Mgc_home/pkgs/siflibs/mgc_io_sync_v2.v 
//------------------------------------------------------------------------------
// Catapult Synthesis - Sample I/O Port Library
//
// Copyright (c) 2003-2017 Mentor Graphics Corp.
//       All Rights Reserved
//
// This document may be used and distributed without restriction provided that
// this copyright statement is not removed from the file and that any derivative
// work contains this copyright notice.
//
// The design information contained in this file is intended to be an example
// of the functionality which the end user may study in preparation for creating
// their own custom interfaces. This design does not necessarily present a 
// complete implementation of the named protocol or standard.
//
//------------------------------------------------------------------------------


module mgc_io_sync_v2 (ld, lz);
    parameter valid = 0;

    input  ld;
    output lz;

    wire   lz;

    assign lz = ld;

endmodule


//------> ./rtl.v 
// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2023.1_2/1049935 Production Release
//  HLS Date:       Sat Jun 10 10:53:51 PDT 2023
// 
//  Generated by:   ajh9498@hansolo.poly.edu
//  Generated date: Fri Feb 28 19:06:51 2025
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    filter_core_core_fsm
//  FSM Module
// ------------------------------------------------------------------


module filter_core_core_fsm (
  clk, rst_n, fsm_output
);
  input clk;
  input rst_n;
  output [1:0] fsm_output;
  reg [1:0] fsm_output;


  // FSM State Type Declaration for filter_core_core_fsm_1
  parameter
    main_C_0 = 1'd0,
    main_C_1 = 1'd1;

  reg  state_var;
  reg  state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : filter_core_core_fsm_1
    case (state_var)
      main_C_1 : begin
        fsm_output = 2'b10;
        state_var_NS = main_C_0;
      end
      // main_C_0
      default : begin
        fsm_output = 2'b01;
        state_var_NS = main_C_1;
      end
    endcase
  end

  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      state_var <= main_C_0;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    filter_core
// ------------------------------------------------------------------


module filter_core (
  clk, rst_n, input_rsc_dat, input_triosy_lz, fir_output_rsc_dat, fir_output_triosy_lz,
      iir_output_rsc_dat, iir_output_triosy_lz
);
  input clk;
  input rst_n;
  input [31:0] input_rsc_dat;
  output input_triosy_lz;
  output [31:0] fir_output_rsc_dat;
  output fir_output_triosy_lz;
  output [31:0] iir_output_rsc_dat;
  output iir_output_triosy_lz;


  // Interconnect Declarations
  wire [31:0] input_rsci_idat;
  reg [31:0] fir_output_rsci_idat;
  wire [32:0] nl_fir_output_rsci_idat;
  reg [31:0] iir_output_rsci_idat;
  wire [32:0] nl_iir_output_rsci_idat;
  wire [1:0] fsm_output;
  reg reg_iir_output_triosy_obj_ld_cse;
  wire [31:0] iir_feedforward_acc_6_cse;
  wire [32:0] nl_iir_feedforward_acc_6_cse;
  wire [30:0] iir_feedforward_acc_9_cse;
  wire [31:0] nl_iir_feedforward_acc_9_cse;
  reg [31:0] iir_in_d0_sva;
  reg [31:0] iir_in_d1_sva;
  reg [31:0] iir_in_d2_sva;
  reg [31:0] iir_in_d3_sva;
  reg [31:0] iir_out_d1_sva;
  reg [31:0] iir_out_d2_sva;
  reg [31:0] iir_feedforward_asn_1_itm;
  reg [31:0] out_d2_asn_itm;

  wire[31:0] iir_feedforward_acc_8_nl;
  wire[33:0] nl_iir_feedforward_acc_8_nl;
  wire[31:0] iir_feedforward_acc_nl;
  wire[33:0] nl_iir_feedforward_acc_nl;
  wire[31:0] fir_acc_acc_7_nl;
  wire[32:0] nl_fir_acc_acc_7_nl;
  wire[31:0] fir_acc_acc_5_nl;
  wire[32:0] nl_fir_acc_acc_5_nl;

  // Interconnect Declarations for Component Instantiations 
  ccs_in_v1 #(.rscid(32'sd1),
  .width(32'sd32)) input_rsci (
      .dat(input_rsc_dat),
      .idat(input_rsci_idat)
    );
  ccs_out_v1 #(.rscid(32'sd2),
  .width(32'sd32)) fir_output_rsci (
      .idat(fir_output_rsci_idat),
      .dat(fir_output_rsc_dat)
    );
  ccs_out_v1 #(.rscid(32'sd3),
  .width(32'sd32)) iir_output_rsci (
      .idat(iir_output_rsci_idat),
      .dat(iir_output_rsc_dat)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) input_triosy_obj (
      .ld(reg_iir_output_triosy_obj_ld_cse),
      .lz(input_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) fir_output_triosy_obj (
      .ld(reg_iir_output_triosy_obj_ld_cse),
      .lz(fir_output_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) iir_output_triosy_obj (
      .ld(reg_iir_output_triosy_obj_ld_cse),
      .lz(iir_output_triosy_lz)
    );
  filter_core_core_fsm filter_core_core_fsm_inst (
      .clk(clk),
      .rst_n(rst_n),
      .fsm_output(fsm_output)
    );
  assign nl_iir_feedforward_acc_6_cse = input_rsci_idat + iir_in_d1_sva;
  assign iir_feedforward_acc_6_cse = nl_iir_feedforward_acc_6_cse[31:0];
  assign nl_iir_feedforward_acc_9_cse = (iir_in_d3_sva[30:0]) + (iir_in_d1_sva[30:0]);
  assign iir_feedforward_acc_9_cse = nl_iir_feedforward_acc_9_cse[30:0];
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_rsci_idat <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ (fsm_output[1]) ) begin
      iir_output_rsci_idat <= nl_iir_output_rsci_idat[31:0];
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      fir_output_rsci_idat <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ (fsm_output[1]) ) begin
      fir_output_rsci_idat <= nl_fir_output_rsci_idat[31:0];
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      reg_iir_output_triosy_obj_ld_cse <= 1'b0;
      iir_feedforward_asn_1_itm <= 32'b00000000000000000000000000000000;
      out_d2_asn_itm <= 32'b00000000000000000000000000000000;
    end
    else begin
      reg_iir_output_triosy_obj_ld_cse <= ~ (fsm_output[1]);
      iir_feedforward_asn_1_itm <= iir_in_d3_sva;
      out_d2_asn_itm <= iir_out_d2_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_in_d1_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ (fsm_output[1]) ) begin
      iir_in_d1_sva <= iir_in_d0_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_in_d0_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ (fsm_output[1]) ) begin
      iir_in_d0_sva <= input_rsci_idat;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_out_d2_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ (fsm_output[0]) ) begin
      iir_out_d2_sva <= iir_out_d1_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_out_d1_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ (fsm_output[0]) ) begin
      iir_out_d1_sva <= iir_output_rsci_idat;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_in_d3_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ (fsm_output[0]) ) begin
      iir_in_d3_sva <= iir_in_d2_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_in_d2_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ (fsm_output[0]) ) begin
      iir_in_d2_sva <= iir_in_d1_sva;
    end
  end
  assign nl_iir_feedforward_acc_8_nl = iir_feedforward_acc_6_cse + iir_feedforward_asn_1_itm
      + iir_out_d2_sva;
  assign iir_feedforward_acc_8_nl = nl_iir_feedforward_acc_8_nl[31:0];
  assign nl_iir_feedforward_acc_nl = ({iir_feedforward_acc_9_cse , 1'b0}) + (~ out_d2_asn_itm)
      + ({(iir_in_d0_sva[30:0]) , 1'b1});
  assign iir_feedforward_acc_nl = nl_iir_feedforward_acc_nl[31:0];
  assign nl_iir_output_rsci_idat  = iir_feedforward_acc_8_nl + iir_feedforward_acc_nl;
  assign nl_fir_acc_acc_5_nl = iir_feedforward_asn_1_itm + ({(iir_in_d0_sva[30:0])
      , 1'b0});
  assign fir_acc_acc_5_nl = nl_fir_acc_acc_5_nl[31:0];
  assign nl_fir_acc_acc_7_nl = fir_acc_acc_5_nl + ({iir_feedforward_acc_9_cse , 1'b0});
  assign fir_acc_acc_7_nl = nl_fir_acc_acc_7_nl[31:0];
  assign nl_fir_output_rsci_idat  = fir_acc_acc_7_nl + iir_feedforward_acc_6_cse;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    filter
// ------------------------------------------------------------------


module filter (
  clk, rst_n, input_rsc_dat, input_triosy_lz, fir_output_rsc_dat, fir_output_triosy_lz,
      iir_output_rsc_dat, iir_output_triosy_lz
);
  input clk;
  input rst_n;
  input [31:0] input_rsc_dat;
  output input_triosy_lz;
  output [31:0] fir_output_rsc_dat;
  output fir_output_triosy_lz;
  output [31:0] iir_output_rsc_dat;
  output iir_output_triosy_lz;



  // Interconnect Declarations for Component Instantiations 
  filter_core filter_core_inst (
      .clk(clk),
      .rst_n(rst_n),
      .input_rsc_dat(input_rsc_dat),
      .input_triosy_lz(input_triosy_lz),
      .fir_output_rsc_dat(fir_output_rsc_dat),
      .fir_output_triosy_lz(fir_output_triosy_lz),
      .iir_output_rsc_dat(iir_output_rsc_dat),
      .iir_output_triosy_lz(iir_output_triosy_lz)
    );
endmodule



