# config file
tcl: "inputs/directives.tcl"
includes: "inputs/aes_to_opt/aes_includes.txt"
orig_code: "inputs/aes_to_opt/aes_funcs.txt"
test_code: "inputs/aes_to_opt/aes_test.txt"
top_function: "Cipher_hls"
hierarchical: True