# config file
tcl: "inputs/directives.tcl"
includes: "inputs/cusums/cusums_inc.txt"
orig_code: "inputs/cusums/cusums.cpp"
test_code: "inputs/cusums/cusums_test.txt"
top_function: "CumulativeSums"
mode: "streaming"