# config file
tcl: "inputs/directives.tcl"
includes: "inputs/sha256/sha256_includes.txt"
orig_code: "inputs/sha256/sha256.c"
test_code: "inputs/sha256/sha256_test.txt"
top_function: "sha256_update"
hierarchical: True