directive set /quickSort/quickSort:core/core/stack(0)#1.sva REGISTER_NAME stack(0)#1.sva
directive set /quickSort/quickSort:core/core/while:while:mux1h.itm REGISTER_NAME stack(0)#1.sva
directive set /quickSort/quickSort:core/core/partition:j.lpi#4 REGISTER_NAME partition:j.lpi#4
directive set /quickSort/quickSort:core/core/partition:j.sva REGISTER_NAME partition:j.lpi#4
directive set /quickSort/quickSort:core/core/partition:i.lpi#4 REGISTER_NAME partition:i.lpi#4
directive set /quickSort/quickSort:core/core/while:if:while:if:acc#3.ctmp.sva REGISTER_NAME partition:i.lpi#4
directive set /quickSort/quickSort:core/core/top#1(31:1).sva#1 REGISTER_NAME top#1(31:1).sva#1
directive set /quickSort/quickSort:core/core/top#1(31:1).sva.dfm REGISTER_NAME top#1(31:1).sva#1
directive set /quickSort/quickSort:core/core/partition:pivot.sva REGISTER_NAME partition:pivot.sva
directive set /quickSort/quickSort:core/core/top#1(31:1).sva(29:0) REGISTER_NAME partition:pivot.sva
directive set /quickSort/quickSort:core/core/while:if:slc(while:if:while:if:acc.psp#1.sva REGISTER_NAME partition:pivot.sva
directive set /quickSort/quickSort:core/core/exit:partition:while.sva REGISTER_NAME exit:partition:while.sva
directive set /quickSort/quickSort:core/core/swap#1:equal.tmp#10 REGISTER_NAME exit:partition:while.sva
directive set /quickSort/quickSort:core/core/while:if:while:if:nor#67.cse.sva REGISTER_NAME exit:partition:while.sva
directive set /quickSort/quickSort:core/core/swap#1:nor#101.itm REGISTER_NAME swap#1:nor#101.itm
directive set /quickSort/quickSort:core/core/while:if:and#369.tmp.sva REGISTER_NAME swap#1:nor#101.itm
directive set /quickSort/quickSort:core/core/swap#1:nor#58.itm REGISTER_NAME swap#1:nor#58.itm
directive set /quickSort/quickSort:core/core/while:if:and.stg_4_31.sva REGISTER_NAME swap#1:nor#58.itm
directive set /quickSort/quickSort:core/core/swap#1:nor#57.itm REGISTER_NAME swap#1:nor#57.itm
directive set /quickSort/quickSort:core/core/while:if:and.stg_4_0.sva REGISTER_NAME swap#1:nor#57.itm
directive set /quickSort/quickSort:core/core/swap#1:nor#56.itm REGISTER_NAME swap#1:nor#56.itm
directive set /quickSort/quickSort:core/core/while:if:and.stg_3_15.sva REGISTER_NAME swap#1:nor#56.itm
directive set /quickSort/quickSort:core/core/swap#1:nor#30.itm REGISTER_NAME swap#1:nor#30.itm
directive set /quickSort/quickSort:core/core/while:if:and.stg_2_7.sva REGISTER_NAME swap#1:nor#30.itm
directive set /quickSort/quickSort:core/core/swap#1:nor#15.itm REGISTER_NAME swap#1:nor#15.itm
directive set /quickSort/quickSort:core/core/while:if:and.stg_1_3.sva REGISTER_NAME swap#1:nor#15.itm
directive set /quickSort/quickSort:core/core/swap#1:nor#11.itm REGISTER_NAME swap#1:nor#11.itm
directive set /quickSort/quickSort:core/core/while:if:and.stg_1_0.sva REGISTER_NAME swap#1:nor#11.itm
directive set /quickSort/quickSort:core/core/swap#1:nor#5.itm REGISTER_NAME swap#1:nor#5.itm
directive set /quickSort/quickSort:core/core/while:if:and.stg_3_0.sva REGISTER_NAME swap#1:nor#5.itm
directive set /quickSort/quickSort:core/core/swap#1:nor#3.itm REGISTER_NAME swap#1:nor#3.itm
directive set /quickSort/quickSort:core/core/while:if:and.stg_2_0.sva REGISTER_NAME swap#1:nor#3.itm
directive set /quickSort/quickSort:core/core/swap#1:nor#1.itm REGISTER_NAME swap#1:nor#1.itm
directive set /quickSort/quickSort:core/core/while:if:and#122.tmp.sva REGISTER_NAME swap#1:nor#1.itm
