directive set /quickSort/quickSort:core/quickSort:core:conc/partition:pivot:mux#64 RESOURCE_NAME partition:pivot:mux#64:rg
directive set /quickSort/quickSort:core/quickSort:core:conc/partition:while:while:mux#1 RESOURCE_NAME partition:pivot:mux#64:rg
directive set /quickSort/quickSort:core/quickSort:core:conc/swap#1:temp:mux RESOURCE_NAME partition:pivot:mux#64:rg
directive set /quickSort/quickSort:core/quickSort:core:conc/while:acc#4 RESOURCE_NAME partition:while:acc#1:rg
directive set /quickSort/quickSort:core/quickSort:core:conc/partition:while:while:acc#1 RESOURCE_NAME partition:while:acc#1:rg
directive set /quickSort/quickSort:core/quickSort:core:conc/partition:while:while#1:acc#1 RESOURCE_NAME partition:while:acc#1:rg
directive set /quickSort/quickSort:core/quickSort:core:conc/while:if:while:if:acc#3 RESOURCE_NAME partition:while:acc#1:rg
directive set /quickSort/quickSort:core/quickSort:core:conc/partition:while:acc#1 RESOURCE_NAME partition:while:acc#1:rg
directive set /quickSort/quickSort:core/quickSort:core:conc/while:if:slc(while:if:while:if:acc#1 RESOURCE_NAME partition:while:acc#1:rg
directive set /quickSort/quickSort:core/quickSort:core:conc/partition:while:while:aif:acc#1 RESOURCE_NAME partition:while:acc#1:rg
directive set /quickSort/quickSort:core/quickSort:core:conc/partition:while:while#1:aif:acc#1 RESOURCE_NAME partition:while:acc#1:rg
directive set /quickSort/quickSort:core/quickSort:core:conc/partition:while:while:acc RESOURCE_NAME partition:while:while#1:acc:rg
directive set /quickSort/quickSort:core/quickSort:core:conc/partition:while:while#1:acc RESOURCE_NAME partition:while:while#1:acc:rg
