
//------> /eda/mentor/Siemens_EDA/Catapult_Synthesis_2023.1_2/Mgc_home/pkgs/siflibs/ccs_in_v1.v 
//------------------------------------------------------------------------------
// Catapult Synthesis - Sample I/O Port Library
//
// Copyright (c) 2003-2017 Mentor Graphics Corp.
//       All Rights Reserved
//
// This document may be used and distributed without restriction provided that
// this copyright statement is not removed from the file and that any derivative
// work contains this copyright notice.
//
// The design information contained in this file is intended to be an example
// of the functionality which the end user may study in preparation for creating
// their own custom interfaces. This design does not necessarily present a 
// complete implementation of the named protocol or standard.
//
//------------------------------------------------------------------------------


module ccs_in_v1 (idat, dat);

  parameter integer rscid = 1;
  parameter integer width = 8;

  output [width-1:0] idat;
  input  [width-1:0] dat;

  wire   [width-1:0] idat;

  assign idat = dat;

endmodule


//------> /eda/mentor/Siemens_EDA/Catapult_Synthesis_2023.1_2/Mgc_home/pkgs/siflibs/ccs_out_v1.v 
//------------------------------------------------------------------------------
// Catapult Synthesis - Sample I/O Port Library
//
// Copyright (c) 2003-2015 Mentor Graphics Corp.
//       All Rights Reserved
//
// This document may be used and distributed without restriction provided that
// this copyright statement is not removed from the file and that any derivative
// work contains this copyright notice.
//
// The design information contained in this file is intended to be an example
// of the functionality which the end user may study in preparation for creating
// their own custom interfaces. This design does not necessarily present a 
// complete implementation of the named protocol or standard.
//
//------------------------------------------------------------------------------

module ccs_out_v1 (dat, idat);

  parameter integer rscid = 1;
  parameter integer width = 8;

  output   [width-1:0] dat;
  input    [width-1:0] idat;

  wire     [width-1:0] dat;

  assign dat = idat;

endmodule




//------> /eda/mentor/Siemens_EDA/Catapult_Synthesis_2023.1_2/Mgc_home/pkgs/siflibs/mgc_io_sync_v2.v 
//------------------------------------------------------------------------------
// Catapult Synthesis - Sample I/O Port Library
//
// Copyright (c) 2003-2017 Mentor Graphics Corp.
//       All Rights Reserved
//
// This document may be used and distributed without restriction provided that
// this copyright statement is not removed from the file and that any derivative
// work contains this copyright notice.
//
// The design information contained in this file is intended to be an example
// of the functionality which the end user may study in preparation for creating
// their own custom interfaces. This design does not necessarily present a 
// complete implementation of the named protocol or standard.
//
//------------------------------------------------------------------------------


module mgc_io_sync_v2 (ld, lz);
    parameter valid = 0;

    input  ld;
    output lz;

    wire   lz;

    assign lz = ld;

endmodule


//------> ./rtl.v 
// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2023.1_2/1049935 Production Release
//  HLS Date:       Sat Jun 10 10:53:51 PDT 2023
// 
//  Generated by:   ajh9498@hansolo.poly.edu
//  Generated date: Fri Feb 28 23:00:34 2025
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    filter_core_core_fsm
//  FSM Module
// ------------------------------------------------------------------


module filter_core_core_fsm (
  clk, rst_n, fsm_output, fir_for_C_0_tr0
);
  input clk;
  input rst_n;
  output [3:0] fsm_output;
  reg [3:0] fsm_output;
  input fir_for_C_0_tr0;


  // FSM State Type Declaration for filter_core_core_fsm_1
  parameter
    main_C_0 = 2'd0,
    fir_for_C_0 = 2'd1,
    main_C_1 = 2'd2,
    main_C_2 = 2'd3;

  reg [1:0] state_var;
  reg [1:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : filter_core_core_fsm_1
    case (state_var)
      fir_for_C_0 : begin
        fsm_output = 4'b0010;
        if ( fir_for_C_0_tr0 ) begin
          state_var_NS = main_C_1;
        end
        else begin
          state_var_NS = fir_for_C_0;
        end
      end
      main_C_1 : begin
        fsm_output = 4'b0100;
        state_var_NS = main_C_2;
      end
      main_C_2 : begin
        fsm_output = 4'b1000;
        state_var_NS = main_C_0;
      end
      // main_C_0
      default : begin
        fsm_output = 4'b0001;
        state_var_NS = fir_for_C_0;
      end
    endcase
  end

  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      state_var <= main_C_0;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    filter_core
// ------------------------------------------------------------------


module filter_core (
  clk, rst_n, input_rsc_dat, input_triosy_lz, fir_output_rsc_dat, fir_output_triosy_lz,
      iir_output_rsc_dat, iir_output_triosy_lz
);
  input clk;
  input rst_n;
  input [31:0] input_rsc_dat;
  output input_triosy_lz;
  output [31:0] fir_output_rsc_dat;
  output fir_output_triosy_lz;
  output [31:0] iir_output_rsc_dat;
  output iir_output_triosy_lz;


  // Interconnect Declarations
  wire [31:0] input_rsci_idat;
  reg [31:0] fir_output_rsci_idat;
  reg input_triosy_obj_ld;
  wire [3:0] fsm_output;
  wire iir_for_1_iir_for_1_nor_tmp;
  wire and_dcpl_1;
  wire or_dcpl_7;
  wire or_dcpl_9;
  wire or_tmp_9;
  reg exit_fir_for_sva;
  wire [1:0] fir_for_i_1_0_sva_3;
  wire [2:0] nl_fir_for_i_1_0_sva_3;
  reg [1:0] fir_for_i_1_0_sva;
  reg reg_iir_output_triosy_obj_ld_cse;
  wire fir_for_fir_for_or_cse;
  wire iir_for_2_and_3_itm;
  wire [31:0] z_out;
  wire [32:0] nl_z_out;
  wire [31:0] z_out_1;
  wire [32:0] nl_z_out_1;
  reg [31:0] iir_input_delay_lane_2_sva;
  reg [31:0] iir_input_delay_lane_1_sva;
  reg [31:0] iir_input_delay_lane_3_sva;
  reg [31:0] iir_input_delay_lane_0_sva;
  reg [31:0] iir_output_delay_lane_2_sva;
  reg [31:0] iir_output_delay_lane_1_sva;
  reg [31:0] iir_output_delay_lane_3_sva;
  reg [31:0] iir_output_delay_lane_4_sva;
  reg [31:0] fir_delay_lane_2_lpi_2;
  reg [31:0] fir_delay_lane_1_lpi_2;
  reg [31:0] fir_delay_lane_3_lpi_2;
  reg [31:0] fir_delay_lane_4_lpi_2;
  reg [31:0] input_sva;
  reg [31:0] iir_feedforward_sva;
  reg [2:0] iir_for_1_i_2_0_sva;
  reg [31:0] iir_feedback_sva;
  reg [2:0] iir_for_2_i_2_0_sva;
  wire [2:0] iir_for_2_i_2_0_sva_2;
  wire [3:0] nl_iir_for_2_i_2_0_sva_2;
  wire [2:0] iir_for_1_i_2_0_sva_2;
  wire [3:0] nl_iir_for_1_i_2_0_sva_2;
  wire [31:0] fir_for_fir_for_slc_fir_delay_lane_32_31_0_1_ctmp_sva_1;
  reg [31:0] reg_iir_output_rsci_idat_cse;
  wire fir_for_acc_itm_2_1;

  wire fir_for_fir_for_xnor_nl;
  wire[3:0] iir_for_1_acc_nl;
  wire[4:0] nl_iir_for_1_acc_nl;
  wire[3:0] iir_for_2_acc_nl;
  wire[4:0] nl_iir_for_2_acc_nl;
  wire[2:0] fir_for_acc_nl;
  wire[3:0] nl_fir_for_acc_nl;
  wire[31:0] fir_for_1_mux_2_nl;
  wire[31:0] fir_for_1_acc_8_nl;
  wire[32:0] nl_fir_for_1_acc_8_nl;
  wire[31:0] fir_for_1_acc_9_nl;
  wire[32:0] nl_fir_for_1_acc_9_nl;
  wire[29:0] fir_for_1_acc_10_nl;
  wire[30:0] nl_fir_for_1_acc_10_nl;
  wire[31:0] fir_for_1_mux_3_nl;
  wire[31:0] fir_for_1_acc_11_nl;
  wire[32:0] nl_fir_for_1_acc_11_nl;
  wire[31:0] iir_for_2_mul_1_nl;
  wire signed [33:0] nl_iir_for_2_mul_1_nl;
  wire[31:0] iir_for_2_mux_1_nl;
  wire iir_for_2_or_2_nl;
  wire[31:0] iir_for_1_mux_3_nl;
  wire[31:0] iir_for_1_mul_1_nl;
  wire signed [34:0] nl_iir_for_1_mul_1_nl;
  wire[31:0] iir_for_1_mux_4_nl;
  wire[1:0] iir_for_1_mux_5_nl;

  // Interconnect Declarations for Component Instantiations 
  ccs_in_v1 #(.rscid(32'sd1),
  .width(32'sd32)) input_rsci (
      .dat(input_rsc_dat),
      .idat(input_rsci_idat)
    );
  ccs_out_v1 #(.rscid(32'sd2),
  .width(32'sd32)) fir_output_rsci (
      .idat(fir_output_rsci_idat),
      .dat(fir_output_rsc_dat)
    );
  ccs_out_v1 #(.rscid(32'sd3),
  .width(32'sd32)) iir_output_rsci (
      .idat(reg_iir_output_rsci_idat_cse),
      .dat(iir_output_rsc_dat)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) input_triosy_obj (
      .ld(input_triosy_obj_ld),
      .lz(input_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) fir_output_triosy_obj (
      .ld(reg_iir_output_triosy_obj_ld_cse),
      .lz(fir_output_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) iir_output_triosy_obj (
      .ld(reg_iir_output_triosy_obj_ld_cse),
      .lz(iir_output_triosy_lz)
    );
  filter_core_core_fsm filter_core_core_fsm_inst (
      .clk(clk),
      .rst_n(rst_n),
      .fsm_output(fsm_output),
      .fir_for_C_0_tr0(and_dcpl_1)
    );
  assign iir_for_2_and_3_itm = (iir_for_2_i_2_0_sva==3'b010);
  assign fir_for_fir_for_or_cse = (~ fir_for_acc_itm_2_1) | exit_fir_for_sva;
  assign nl_iir_for_2_i_2_0_sva_2 = iir_for_2_i_2_0_sva + 3'b001;
  assign iir_for_2_i_2_0_sva_2 = nl_iir_for_2_i_2_0_sva_2[2:0];
  assign nl_iir_for_1_i_2_0_sva_2 = iir_for_1_i_2_0_sva + 3'b001;
  assign iir_for_1_i_2_0_sva_2 = nl_iir_for_1_i_2_0_sva_2[2:0];
  assign fir_for_fir_for_xnor_nl = ~((fir_for_i_1_0_sva[0]) ^ (fir_for_i_1_0_sva[1]));
  assign fir_for_fir_for_slc_fir_delay_lane_32_31_0_1_ctmp_sva_1 = MUX_v_32_4_2(fir_delay_lane_1_lpi_2,
      iir_input_delay_lane_0_sva, fir_delay_lane_3_lpi_2, fir_delay_lane_2_lpi_2,
      {fir_for_fir_for_xnor_nl , (fir_for_i_1_0_sva[0])});
  assign nl_fir_for_i_1_0_sva_3 = fir_for_i_1_0_sva + 2'b11;
  assign fir_for_i_1_0_sva_3 = nl_fir_for_i_1_0_sva_3[1:0];
  assign nl_iir_for_1_acc_nl = conv_u2s_3_4(iir_for_1_i_2_0_sva_2) + 4'b1011;
  assign iir_for_1_acc_nl = nl_iir_for_1_acc_nl[3:0];
  assign nl_iir_for_2_acc_nl = conv_u2s_3_4(iir_for_2_i_2_0_sva_2) + 4'b1011;
  assign iir_for_2_acc_nl = nl_iir_for_2_acc_nl[3:0];
  assign iir_for_1_iir_for_1_nor_tmp = ~((readslicef_4_1_3(iir_for_1_acc_nl)) | (readslicef_4_1_3(iir_for_2_acc_nl)));
  assign and_dcpl_1 = fir_for_fir_for_or_cse & iir_for_1_iir_for_1_nor_tmp;
  assign or_dcpl_7 = exit_fir_for_sva | (fir_for_i_1_0_sva[1]);
  assign or_dcpl_9 = exit_fir_for_sva | (~ (fir_for_i_1_0_sva[1]));
  assign or_tmp_9 = ~((fsm_output[1]) & (~((~ exit_fir_for_sva) & fir_for_acc_itm_2_1))
      & iir_for_1_iir_for_1_nor_tmp);
  assign nl_fir_for_acc_nl = ({1'b1 , (~ fir_for_i_1_0_sva_3)}) + 3'b001;
  assign fir_for_acc_nl = nl_fir_for_acc_nl[2:0];
  assign fir_for_acc_itm_2_1 = readslicef_3_1_2(fir_for_acc_nl);
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      input_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( fsm_output[0] ) begin
      input_sva <= input_rsci_idat;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      reg_iir_output_rsci_idat_cse <= 32'b00000000000000000000000000000000;
    end
    else if ( fsm_output[2] ) begin
      reg_iir_output_rsci_idat_cse <= z_out_1;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      fir_output_rsci_idat <= 32'b00000000000000000000000000000000;
    end
    else if ( fsm_output[2] ) begin
      fir_output_rsci_idat <= z_out;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_for_2_i_2_0_sva <= 3'b000;
      iir_feedback_sva <= 32'b00000000000000000000000000000000;
      iir_for_1_i_2_0_sva <= 3'b000;
      iir_feedforward_sva <= 32'b00000000000000000000000000000000;
      exit_fir_for_sva <= 1'b0;
      fir_for_i_1_0_sva <= 2'b00;
      reg_iir_output_triosy_obj_ld_cse <= 1'b0;
      input_triosy_obj_ld <= 1'b0;
    end
    else begin
      iir_for_2_i_2_0_sva <= MUX_v_3_2_2(3'b000, iir_for_2_i_2_0_sva_2, (fsm_output[1]));
      iir_feedback_sva <= MUX_v_32_2_2(32'b00000000000000000000000000000000, z_out,
          (fsm_output[1]));
      iir_for_1_i_2_0_sva <= MUX_v_3_2_2(3'b000, iir_for_1_i_2_0_sva_2, (fsm_output[1]));
      iir_feedforward_sva <= MUX_v_32_2_2(32'b00000000000000000000000000000000, z_out_1,
          (fsm_output[1]));
      exit_fir_for_sva <= fir_for_fir_for_or_cse & (fsm_output[1]);
      fir_for_i_1_0_sva <= MUX_v_2_2_2(2'b00, fir_for_i_1_0_sva_3, (fsm_output[1]));
      reg_iir_output_triosy_obj_ld_cse <= fsm_output[2];
      input_triosy_obj_ld <= and_dcpl_1 & (fsm_output[1]);
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_1_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_9 ) begin
      iir_output_delay_lane_1_sva <= reg_iir_output_rsci_idat_cse;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_2_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_9 ) begin
      iir_output_delay_lane_2_sva <= iir_output_delay_lane_1_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_3_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_9 ) begin
      iir_output_delay_lane_3_sva <= iir_output_delay_lane_2_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_4_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_9 ) begin
      iir_output_delay_lane_4_sva <= iir_output_delay_lane_3_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_input_delay_lane_0_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( fsm_output[2] ) begin
      iir_input_delay_lane_0_sva <= input_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_input_delay_lane_1_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_9 ) begin
      iir_input_delay_lane_1_sva <= iir_input_delay_lane_0_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_input_delay_lane_2_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_9 ) begin
      iir_input_delay_lane_2_sva <= iir_input_delay_lane_1_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_input_delay_lane_3_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_9 ) begin
      iir_input_delay_lane_3_sva <= iir_input_delay_lane_2_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      fir_delay_lane_4_lpi_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( ~((~(fir_for_fir_for_or_cse | (fir_for_i_1_0_sva_3!=2'b00))) | or_dcpl_7
        | (fir_for_i_1_0_sva[0])) ) begin
      fir_delay_lane_4_lpi_2 <= fir_for_fir_for_slc_fir_delay_lane_32_31_0_1_ctmp_sva_1;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      fir_delay_lane_3_lpi_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( ~((~ (fsm_output[1])) | or_dcpl_9 | (~ (fir_for_i_1_0_sva[0]))) ) begin
      fir_delay_lane_3_lpi_2 <= fir_for_fir_for_slc_fir_delay_lane_32_31_0_1_ctmp_sva_1;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      fir_delay_lane_2_lpi_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( ~((~ (fsm_output[1])) | or_dcpl_9 | (fir_for_i_1_0_sva[0])) ) begin
      fir_delay_lane_2_lpi_2 <= fir_for_fir_for_slc_fir_delay_lane_32_31_0_1_ctmp_sva_1;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      fir_delay_lane_1_lpi_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( ~((~ (fsm_output[1])) | or_dcpl_7 | (~ (fir_for_i_1_0_sva[0]))) ) begin
      fir_delay_lane_1_lpi_2 <= fir_for_fir_for_slc_fir_delay_lane_32_31_0_1_ctmp_sva_1;
    end
  end
  assign nl_fir_for_1_acc_9_nl = fir_delay_lane_4_lpi_2 + ({(fir_delay_lane_1_lpi_2[30:0])
      , 1'b1});
  assign fir_for_1_acc_9_nl = nl_fir_for_1_acc_9_nl[31:0];
  assign nl_fir_for_1_acc_10_nl = (fir_delay_lane_3_lpi_2[30:1]) + (fir_delay_lane_2_lpi_2[29:0]);
  assign fir_for_1_acc_10_nl = nl_fir_for_1_acc_10_nl[29:0];
  assign nl_fir_for_1_acc_8_nl = fir_for_1_acc_9_nl + ({fir_for_1_acc_10_nl , (fir_delay_lane_3_lpi_2[0])
      , 1'b0});
  assign fir_for_1_acc_8_nl = nl_fir_for_1_acc_8_nl[31:0];
  assign fir_for_1_mux_2_nl = MUX_v_32_2_2(fir_for_1_acc_8_nl, iir_feedback_sva,
      fsm_output[1]);
  assign nl_fir_for_1_acc_11_nl = input_sva + (~ fir_delay_lane_2_lpi_2);
  assign fir_for_1_acc_11_nl = nl_fir_for_1_acc_11_nl[31:0];
  assign iir_for_2_mux_1_nl = MUX_v_32_5_2(reg_iir_output_rsci_idat_cse, iir_output_delay_lane_1_sva,
      iir_output_delay_lane_2_sva, iir_output_delay_lane_3_sva, iir_output_delay_lane_4_sva,
      iir_for_2_i_2_0_sva);
  assign iir_for_2_or_2_nl = (~((~((iir_for_2_i_2_0_sva!=3'b000))) | ((iir_for_2_i_2_0_sva==3'b011))
      | ((iir_for_2_i_2_0_sva==3'b100)))) | iir_for_2_and_3_itm;
  assign nl_iir_for_2_mul_1_nl = $signed(iir_for_2_mux_1_nl) * $signed(({iir_for_2_and_3_itm
      , iir_for_2_or_2_nl}));
  assign iir_for_2_mul_1_nl = nl_iir_for_2_mul_1_nl[31:0];
  assign fir_for_1_mux_3_nl = MUX_v_32_2_2(fir_for_1_acc_11_nl, iir_for_2_mul_1_nl,
      fsm_output[1]);
  assign nl_z_out = fir_for_1_mux_2_nl + fir_for_1_mux_3_nl;
  assign z_out = nl_z_out[31:0];
  assign iir_for_1_mux_4_nl = MUX_v_32_5_2(input_sva, iir_input_delay_lane_0_sva,
      iir_input_delay_lane_1_sva, iir_input_delay_lane_2_sva, iir_input_delay_lane_3_sva,
      iir_for_1_i_2_0_sva);
  assign iir_for_1_mux_5_nl = MUX_v_2_5_2(2'b01, 2'b10, 2'b11, 2'b10, 2'b01, iir_for_1_i_2_0_sva);
  assign nl_iir_for_1_mul_1_nl = $signed(iir_for_1_mux_4_nl) * $signed(conv_u2s_2_3(iir_for_1_mux_5_nl));
  assign iir_for_1_mul_1_nl = nl_iir_for_1_mul_1_nl[31:0];
  assign iir_for_1_mux_3_nl = MUX_v_32_2_2(iir_for_1_mul_1_nl, iir_feedback_sva,
      fsm_output[2]);
  assign nl_z_out_1 = iir_feedforward_sva + iir_for_1_mux_3_nl;
  assign z_out_1 = nl_z_out_1[31:0];

  function automatic [1:0] MUX_v_2_2_2;
    input [1:0] input_0;
    input [1:0] input_1;
    input  sel;
    reg [1:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_2_2_2 = result;
  end
  endfunction


  function automatic [1:0] MUX_v_2_5_2;
    input [1:0] input_0;
    input [1:0] input_1;
    input [1:0] input_2;
    input [1:0] input_3;
    input [1:0] input_4;
    input [2:0] sel;
    reg [1:0] result;
  begin
    case (sel)
      3'b000 : begin
        result = input_0;
      end
      3'b001 : begin
        result = input_1;
      end
      3'b010 : begin
        result = input_2;
      end
      3'b011 : begin
        result = input_3;
      end
      default : begin
        result = input_4;
      end
    endcase
    MUX_v_2_5_2 = result;
  end
  endfunction


  function automatic [31:0] MUX_v_32_2_2;
    input [31:0] input_0;
    input [31:0] input_1;
    input  sel;
    reg [31:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_32_2_2 = result;
  end
  endfunction


  function automatic [31:0] MUX_v_32_4_2;
    input [31:0] input_0;
    input [31:0] input_1;
    input [31:0] input_2;
    input [31:0] input_3;
    input [1:0] sel;
    reg [31:0] result;
  begin
    case (sel)
      2'b00 : begin
        result = input_0;
      end
      2'b01 : begin
        result = input_1;
      end
      2'b10 : begin
        result = input_2;
      end
      default : begin
        result = input_3;
      end
    endcase
    MUX_v_32_4_2 = result;
  end
  endfunction


  function automatic [31:0] MUX_v_32_5_2;
    input [31:0] input_0;
    input [31:0] input_1;
    input [31:0] input_2;
    input [31:0] input_3;
    input [31:0] input_4;
    input [2:0] sel;
    reg [31:0] result;
  begin
    case (sel)
      3'b000 : begin
        result = input_0;
      end
      3'b001 : begin
        result = input_1;
      end
      3'b010 : begin
        result = input_2;
      end
      3'b011 : begin
        result = input_3;
      end
      default : begin
        result = input_4;
      end
    endcase
    MUX_v_32_5_2 = result;
  end
  endfunction


  function automatic [2:0] MUX_v_3_2_2;
    input [2:0] input_0;
    input [2:0] input_1;
    input  sel;
    reg [2:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_3_2_2 = result;
  end
  endfunction


  function automatic [0:0] readslicef_3_1_2;
    input [2:0] vector;
    reg [2:0] tmp;
  begin
    tmp = vector >> 2;
    readslicef_3_1_2 = tmp[0:0];
  end
  endfunction


  function automatic [0:0] readslicef_4_1_3;
    input [3:0] vector;
    reg [3:0] tmp;
  begin
    tmp = vector >> 3;
    readslicef_4_1_3 = tmp[0:0];
  end
  endfunction


  function automatic [2:0] conv_u2s_2_3 ;
    input [1:0]  vector ;
  begin
    conv_u2s_2_3 =  {1'b0, vector};
  end
  endfunction


  function automatic [3:0] conv_u2s_3_4 ;
    input [2:0]  vector ;
  begin
    conv_u2s_3_4 =  {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    filter
// ------------------------------------------------------------------


module filter (
  clk, rst_n, input_rsc_dat, input_triosy_lz, fir_output_rsc_dat, fir_output_triosy_lz,
      iir_output_rsc_dat, iir_output_triosy_lz
);
  input clk;
  input rst_n;
  input [31:0] input_rsc_dat;
  output input_triosy_lz;
  output [31:0] fir_output_rsc_dat;
  output fir_output_triosy_lz;
  output [31:0] iir_output_rsc_dat;
  output iir_output_triosy_lz;



  // Interconnect Declarations for Component Instantiations 
  filter_core filter_core_inst (
      .clk(clk),
      .rst_n(rst_n),
      .input_rsc_dat(input_rsc_dat),
      .input_triosy_lz(input_triosy_lz),
      .fir_output_rsc_dat(fir_output_rsc_dat),
      .fir_output_triosy_lz(fir_output_triosy_lz),
      .iir_output_rsc_dat(iir_output_rsc_dat),
      .iir_output_triosy_lz(iir_output_triosy_lz)
    );
endmodule



