import gdb
gdb.execute("file tmp/to_debug")
gdb.execute("break sha256_update")
gdb.execute("run")
gdb.execute("p/x *data_int")
gdb.execute("p/x *datalen_int")
gdb.execute("p/x *state")
gdb.execute("p/x *bitlen_int")
gdb.execute("p/x *data")
gdb.execute("p/x len")
gdb.execute("continue")
