# config file
tcl: "inputs/directives.tcl"
includes: "inputs/ascon/ascon_inc.txt"
orig_code: "inputs/ascon/src/ascon.c"
test_code: "inputs/ascon/ascon_test.txt"
top_function: "encrypt"
hierarchical: True