# config file
tcl: "inputs/directives.tcl"
includes: "inputs/present/present_inc.h"
orig_code: "inputs/present/present.c"
test_code: "inputs/present/present_test.c"
top_function: "present80_encryptBlock"
hierarchical: True