# config file
tcl: "inputs/directives.tcl"
includes: "inputs/overlapping/overlapping_inc.txt"
orig_code: "inputs/overlapping/overlapping.cpp"
test_code: "inputs/overlapping/overlapping_test.txt"
top_function: "Overlapping"
mode: "streaming"