# config file
tcl: "inputs/directives.tcl"
includes: "inputs/monobit/monobit_inc.txt"
orig_code: "inputs/monobit/monobit.cpp"
test_code: "inputs/monobit/monobit_test.txt"
top_function: "Frequency"
mode: "streaming"