
//------> /eda/mentor/Siemens_EDA/Catapult_Synthesis_2023.1_2/Mgc_home/pkgs/siflibs/ccs_in_v1.v 
//------------------------------------------------------------------------------
// Catapult Synthesis - Sample I/O Port Library
//
// Copyright (c) 2003-2017 Mentor Graphics Corp.
//       All Rights Reserved
//
// This document may be used and distributed without restriction provided that
// this copyright statement is not removed from the file and that any derivative
// work contains this copyright notice.
//
// The design information contained in this file is intended to be an example
// of the functionality which the end user may study in preparation for creating
// their own custom interfaces. This design does not necessarily present a 
// complete implementation of the named protocol or standard.
//
//------------------------------------------------------------------------------


module ccs_in_v1 (idat, dat);

  parameter integer rscid = 1;
  parameter integer width = 8;

  output [width-1:0] idat;
  input  [width-1:0] dat;

  wire   [width-1:0] idat;

  assign idat = dat;

endmodule


//------> /eda/mentor/Siemens_EDA/Catapult_Synthesis_2023.1_2/Mgc_home/pkgs/siflibs/ccs_out_v1.v 
//------------------------------------------------------------------------------
// Catapult Synthesis - Sample I/O Port Library
//
// Copyright (c) 2003-2015 Mentor Graphics Corp.
//       All Rights Reserved
//
// This document may be used and distributed without restriction provided that
// this copyright statement is not removed from the file and that any derivative
// work contains this copyright notice.
//
// The design information contained in this file is intended to be an example
// of the functionality which the end user may study in preparation for creating
// their own custom interfaces. This design does not necessarily present a 
// complete implementation of the named protocol or standard.
//
//------------------------------------------------------------------------------

module ccs_out_v1 (dat, idat);

  parameter integer rscid = 1;
  parameter integer width = 8;

  output   [width-1:0] dat;
  input    [width-1:0] idat;

  wire     [width-1:0] dat;

  assign dat = idat;

endmodule




//------> /eda/mentor/Siemens_EDA/Catapult_Synthesis_2023.1_2/Mgc_home/pkgs/siflibs/mgc_io_sync_v2.v 
//------------------------------------------------------------------------------
// Catapult Synthesis - Sample I/O Port Library
//
// Copyright (c) 2003-2017 Mentor Graphics Corp.
//       All Rights Reserved
//
// This document may be used and distributed without restriction provided that
// this copyright statement is not removed from the file and that any derivative
// work contains this copyright notice.
//
// The design information contained in this file is intended to be an example
// of the functionality which the end user may study in preparation for creating
// their own custom interfaces. This design does not necessarily present a 
// complete implementation of the named protocol or standard.
//
//------------------------------------------------------------------------------


module mgc_io_sync_v2 (ld, lz);
    parameter valid = 0;

    input  ld;
    output lz;

    wire   lz;

    assign lz = ld;

endmodule


//------> ./rtl.v 
// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2023.1_2/1049935 Production Release
//  HLS Date:       Sat Jun 10 10:53:51 PDT 2023
// 
//  Generated by:   ajh9498@hansolo.poly.edu
//  Generated date: Fri Feb 28 22:22:45 2025
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    filter_core_core_fsm
//  FSM Module
// ------------------------------------------------------------------


module filter_core_core_fsm (
  clk, rst_n, fsm_output, iir_for_C_0_tr0, iir_for_1_C_0_tr0, iir_for_3_C_0_tr0
);
  input clk;
  input rst_n;
  output [7:0] fsm_output;
  reg [7:0] fsm_output;
  input iir_for_C_0_tr0;
  input iir_for_1_C_0_tr0;
  input iir_for_3_C_0_tr0;


  // FSM State Type Declaration for filter_core_core_fsm_1
  parameter
    main_C_0 = 3'd0,
    main_C_1 = 3'd1,
    iir_for_C_0 = 3'd2,
    iir_for_1_C_0 = 3'd3,
    main_C_2 = 3'd4,
    main_C_3 = 3'd5,
    iir_for_3_C_0 = 3'd6,
    main_C_4 = 3'd7;

  reg [2:0] state_var;
  reg [2:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : filter_core_core_fsm_1
    case (state_var)
      main_C_1 : begin
        fsm_output = 8'b00000010;
        state_var_NS = iir_for_C_0;
      end
      iir_for_C_0 : begin
        fsm_output = 8'b00000100;
        if ( iir_for_C_0_tr0 ) begin
          state_var_NS = iir_for_1_C_0;
        end
        else begin
          state_var_NS = iir_for_C_0;
        end
      end
      iir_for_1_C_0 : begin
        fsm_output = 8'b00001000;
        if ( iir_for_1_C_0_tr0 ) begin
          state_var_NS = main_C_2;
        end
        else begin
          state_var_NS = iir_for_1_C_0;
        end
      end
      main_C_2 : begin
        fsm_output = 8'b00010000;
        state_var_NS = main_C_3;
      end
      main_C_3 : begin
        fsm_output = 8'b00100000;
        state_var_NS = iir_for_3_C_0;
      end
      iir_for_3_C_0 : begin
        fsm_output = 8'b01000000;
        if ( iir_for_3_C_0_tr0 ) begin
          state_var_NS = main_C_4;
        end
        else begin
          state_var_NS = iir_for_3_C_0;
        end
      end
      main_C_4 : begin
        fsm_output = 8'b10000000;
        state_var_NS = main_C_0;
      end
      // main_C_0
      default : begin
        fsm_output = 8'b00000001;
        state_var_NS = main_C_1;
      end
    endcase
  end

  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      state_var <= main_C_0;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    filter_core
// ------------------------------------------------------------------


module filter_core (
  clk, rst_n, input_rsc_dat, input_triosy_lz, fir_output_rsc_dat, fir_output_triosy_lz,
      iir_output_rsc_dat, iir_output_triosy_lz
);
  input clk;
  input rst_n;
  input [31:0] input_rsc_dat;
  output input_triosy_lz;
  output [31:0] fir_output_rsc_dat;
  output fir_output_triosy_lz;
  output [31:0] iir_output_rsc_dat;
  output iir_output_triosy_lz;


  // Interconnect Declarations
  wire [31:0] input_rsci_idat;
  reg [31:0] fir_output_rsci_idat;
  reg [31:0] iir_output_rsci_idat;
  wire [7:0] fsm_output;
  wire and_dcpl_4;
  wire and_dcpl_5;
  wire and_dcpl_6;
  wire or_tmp_16;
  wire or_tmp_21;
  wire and_69_cse;
  reg iir_feedforward_1_0_sva;
  reg iir_for_3_i_2_sva;
  reg reg_iir_output_triosy_obj_ld_cse;
  reg [31:0] reg_iir_input_delay_lane_0_cse;
  wire [31:0] iir_for_1_1_mul_itm;
  wire signed [34:0] nl_iir_for_1_1_mul_itm;
  wire [31:0] z_out;
  wire [32:0] nl_z_out;
  wire [31:0] z_out_1;
  wire [32:0] nl_z_out_1;
  wire [31:0] z_out_2;
  wire [32:0] nl_z_out_2;
  wire [31:0] z_out_3;
  wire [32:0] nl_z_out_3;
  wire [31:0] z_out_4;
  wire [32:0] nl_z_out_4;
  reg [31:0] fir_delay_lane_2_sva;
  reg [31:0] fir_delay_lane_1_sva;
  reg [31:0] fir_delay_lane_3_sva;
  reg [31:0] iir_output_delay_lane_2_sva;
  reg [31:0] iir_output_delay_lane_1_sva;
  reg [31:0] iir_output_delay_lane_0_sva;
  reg [31:0] iir_input_delay_lane_2_lpi_2;
  reg [31:0] iir_input_delay_lane_3_lpi_2;
  reg [31:0] iir_output_delay_lane_2_lpi_2;
  reg [31:0] iir_output_delay_lane_4_lpi_2;
  reg [31:0] iir_output_delay_lane_1_lpi_2;
  reg [31:0] iir_output_delay_lane_3_lpi_2;
  reg [31:0] input_sva;
  reg [30:0] iir_feedforward_1_31_1_sva;
  reg [31:0] iir_feedback_1_sva;
  wire fir_delay_lane_3_sva_mx0c0;
  wire fir_delay_lane_3_sva_mx0c1;
  reg iir_for_1_i_2_1_sva_1;
  reg iir_for_1_i_2_1_sva_0;
  reg iir_for_2_i_2_1_sva_1;
  reg iir_for_2_i_2_1_sva_0;

  wire[31:0] iir_iir_mux1h_nl;
  wire iir_iir_nor_nl;
  wire iir_and_1_nl;
  wire iir_feedback_not_1_nl;
  wire[30:0] iir_for_1_acc_nl;
  wire[31:0] nl_iir_for_1_acc_nl;
  wire[30:0] iir_for_1_2_slc_iir_iir_for_1_mux_nl;
  wire[31:0] iir_for_1_1_slc_iir_iir_for_1_mux_nl;
  wire[30:0] fir_for_1_mux_13_nl;
  wire fir_for_1_fir_for_1_or_1_nl;
  wire[30:0] fir_for_1_mux_14_nl;
  wire fir_for_1_mux_15_nl;
  wire[29:0] fir_for_1_mux_16_nl;
  wire fir_for_1_mux_17_nl;
  wire fir_for_1_fir_for_1_and_1_nl;
  wire[31:0] fir_for_1_mux_18_nl;
  wire[31:0] fir_for_1_mux_19_nl;
  wire[31:0] iir_for_2_1_iir_for_2_and_1_nl;
  wire[31:0] fir_for_1_mux_20_nl;
  wire[31:0] fir_for_1_mux_21_nl;
  wire[31:0] iir_for_2_2_iir_for_2_and_1_nl;
  wire iir_for_2_not_5_nl;
  wire[31:0] fir_for_1_mux_22_nl;
  wire[31:0] iir_for_2_1_slc_iir_iir_for_2_mux_1_nl;
  wire[29:0] fir_for_1_mux_23_nl;

  // Interconnect Declarations for Component Instantiations 
  ccs_in_v1 #(.rscid(32'sd1),
  .width(32'sd32)) input_rsci (
      .dat(input_rsc_dat),
      .idat(input_rsci_idat)
    );
  ccs_out_v1 #(.rscid(32'sd2),
  .width(32'sd32)) fir_output_rsci (
      .idat(fir_output_rsci_idat),
      .dat(fir_output_rsc_dat)
    );
  ccs_out_v1 #(.rscid(32'sd3),
  .width(32'sd32)) iir_output_rsci (
      .idat(iir_output_rsci_idat),
      .dat(iir_output_rsc_dat)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) input_triosy_obj (
      .ld(reg_iir_output_triosy_obj_ld_cse),
      .lz(input_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) fir_output_triosy_obj (
      .ld(reg_iir_output_triosy_obj_ld_cse),
      .lz(fir_output_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) iir_output_triosy_obj (
      .ld(reg_iir_output_triosy_obj_ld_cse),
      .lz(iir_output_triosy_lz)
    );
  filter_core_core_fsm filter_core_core_fsm_inst (
      .clk(clk),
      .rst_n(rst_n),
      .fsm_output(fsm_output),
      .iir_for_C_0_tr0(iir_feedforward_1_0_sva),
      .iir_for_1_C_0_tr0(and_dcpl_4),
      .iir_for_3_C_0_tr0(iir_feedforward_1_0_sva)
    );
  assign iir_for_1_1_slc_iir_iir_for_1_mux_nl = MUX_v_32_3_2(input_sva, iir_input_delay_lane_2_lpi_2,
      fir_delay_lane_3_sva, {iir_for_1_i_2_1_sva_1 , iir_for_1_i_2_1_sva_0});
  assign nl_iir_for_1_1_mul_itm = $signed(iir_for_1_1_slc_iir_iir_for_1_mux_nl) *
      $signed(conv_u2s_2_3({iir_for_1_i_2_1_sva_0 , 1'b1}));
  assign iir_for_1_1_mul_itm = nl_iir_for_1_1_mul_itm[31:0];
  assign and_dcpl_4 = iir_for_2_i_2_1_sva_1 & iir_for_1_i_2_1_sva_1;
  assign and_dcpl_5 = ~((fsm_output[7]) | (fsm_output[0]));
  assign and_dcpl_6 = (~ iir_feedforward_1_0_sva) & iir_for_3_i_2_sva;
  assign or_tmp_16 = ~((fsm_output[6]) & iir_feedforward_1_0_sva);
  assign or_tmp_21 = iir_feedforward_1_0_sva & (fsm_output[6]);
  assign and_69_cse = iir_feedforward_1_0_sva & (fsm_output[2]);
  assign fir_delay_lane_3_sva_mx0c0 = and_dcpl_6 & (fsm_output[2]);
  assign fir_delay_lane_3_sva_mx0c1 = and_dcpl_4 & (fsm_output[3]);
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      fir_output_rsci_idat <= 32'b00000000000000000000000000000000;
    end
    else if ( fsm_output[0] ) begin
      fir_output_rsci_idat <= z_out_3;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_rsci_idat <= 32'b00000000000000000000000000000000;
    end
    else if ( fsm_output[4] ) begin
      iir_output_rsci_idat <= z_out;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_0_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_16 ) begin
      iir_output_delay_lane_0_sva <= fir_delay_lane_3_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_2_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( fsm_output[6] ) begin
      iir_output_delay_lane_2_sva <= MUX_v_32_2_2(iir_output_delay_lane_1_lpi_2,
          iir_output_delay_lane_2_lpi_2, iir_for_3_i_2_sva);
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      input_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ and_dcpl_5 ) begin
      input_sva <= input_rsci_idat;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_1_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( fsm_output[6] ) begin
      iir_output_delay_lane_1_sva <= iir_output_delay_lane_0_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      reg_iir_input_delay_lane_0_cse <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_16 ) begin
      reg_iir_input_delay_lane_0_cse <= input_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      reg_iir_output_triosy_obj_ld_cse <= 1'b0;
      iir_feedforward_1_0_sva <= 1'b0;
      iir_for_3_i_2_sva <= 1'b0;
      iir_for_1_i_2_1_sva_1 <= 1'b0;
      iir_for_1_i_2_1_sva_0 <= 1'b0;
      iir_for_2_i_2_1_sva_1 <= 1'b0;
      iir_for_2_i_2_1_sva_0 <= 1'b0;
      iir_feedforward_1_31_1_sva <= 31'b0000000000000000000000000000000;
    end
    else begin
      reg_iir_output_triosy_obj_ld_cse <= or_tmp_21;
      iir_feedforward_1_0_sva <= ((z_out_1[0]) | (fsm_output[6]) | ((~ iir_feedforward_1_0_sva)
          & (fsm_output[2]))) & (~((~((fsm_output[3]) | (fsm_output[2]) | (fsm_output[6])))
          | and_69_cse));
      iir_for_3_i_2_sva <= ~((fsm_output[2]) | (fsm_output[6]));
      iir_for_1_i_2_1_sva_1 <= iir_for_1_i_2_1_sva_0 & (fsm_output[3]);
      iir_for_1_i_2_1_sva_0 <= (~ iir_for_1_i_2_1_sva_0) & (fsm_output[3]);
      iir_for_2_i_2_1_sva_1 <= iir_for_2_i_2_1_sva_0 & (fsm_output[3]);
      iir_for_2_i_2_1_sva_0 <= (~ iir_for_2_i_2_1_sva_0) & (fsm_output[3]);
      iir_feedforward_1_31_1_sva <= MUX_v_31_2_2(31'b0000000000000000000000000000000,
          iir_for_1_acc_nl, (fsm_output[3]));
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      fir_delay_lane_3_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( fir_delay_lane_3_sva_mx0c0 | fir_delay_lane_3_sva_mx0c1 | (fsm_output[4])
        | or_tmp_21 ) begin
      fir_delay_lane_3_sva <= MUX1HOT_v_32_4_2(iir_input_delay_lane_3_lpi_2, z_out_1,
          z_out, fir_delay_lane_2_sva, {fir_delay_lane_3_sva_mx0c0 , fir_delay_lane_3_sva_mx0c1
          , (fsm_output[4]) , or_tmp_21});
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      fir_delay_lane_2_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_16 ) begin
      fir_delay_lane_2_sva <= fir_delay_lane_1_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      fir_delay_lane_1_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_16 ) begin
      fir_delay_lane_1_sva <= reg_iir_input_delay_lane_0_cse;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_3_lpi_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( ~((~ (fsm_output[6])) | iir_feedforward_1_0_sva) ) begin
      iir_output_delay_lane_3_lpi_2 <= iir_output_delay_lane_2_lpi_2;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_input_delay_lane_2_lpi_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( (fsm_output[2]) & iir_feedforward_1_0_sva & (~ iir_for_3_i_2_sva) )
        begin
      iir_input_delay_lane_2_lpi_2 <= iir_feedback_1_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_input_delay_lane_3_lpi_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( ~((~ (fsm_output[2])) | iir_feedforward_1_0_sva) ) begin
      iir_input_delay_lane_3_lpi_2 <= iir_input_delay_lane_2_lpi_2;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_4_lpi_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( and_dcpl_6 & (fsm_output[6]) ) begin
      iir_output_delay_lane_4_lpi_2 <= iir_output_delay_lane_3_lpi_2;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_feedback_1_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( and_69_cse | (fsm_output[3]) | (fsm_output[6]) ) begin
      iir_feedback_1_sva <= MUX_v_32_2_2(32'b00000000000000000000000000000000, iir_iir_mux1h_nl,
          iir_feedback_not_1_nl);
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_1_lpi_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( ~(and_dcpl_5 & (~ (fsm_output[1]))) ) begin
      iir_output_delay_lane_1_lpi_2 <= iir_output_delay_lane_1_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_2_lpi_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( fsm_output[1] ) begin
      iir_output_delay_lane_2_lpi_2 <= iir_output_delay_lane_2_sva;
    end
  end
  assign iir_for_1_2_slc_iir_iir_for_1_mux_nl = MUX_v_31_2_2((reg_iir_input_delay_lane_0_cse[30:0]),
      (iir_input_delay_lane_3_lpi_2[30:0]), iir_for_1_i_2_1_sva_0);
  assign nl_iir_for_1_acc_nl = (z_out_1[31:1]) + iir_for_1_2_slc_iir_iir_for_1_mux_nl;
  assign iir_for_1_acc_nl = nl_iir_for_1_acc_nl[30:0];
  assign iir_iir_nor_nl = ~(iir_for_2_i_2_1_sva_1 | (fsm_output[6]));
  assign iir_and_1_nl = iir_for_2_i_2_1_sva_1 & (~ (fsm_output[6]));
  assign iir_iir_mux1h_nl = MUX1HOT_v_32_3_2(z_out_3, z_out_2, reg_iir_input_delay_lane_0_cse,
      {iir_iir_nor_nl , iir_and_1_nl , (fsm_output[6])});
  assign iir_feedback_not_1_nl = ~ and_69_cse;
  assign fir_for_1_mux_13_nl = MUX_v_31_2_2((reg_iir_input_delay_lane_0_cse[30:0]),
      (iir_feedback_1_sva[31:1]), fsm_output[4]);
  assign fir_for_1_fir_for_1_or_1_nl = (iir_feedback_1_sva[0]) | (~ (fsm_output[4]));
  assign nl_z_out = fir_delay_lane_3_sva + ({fir_for_1_mux_13_nl , fir_for_1_fir_for_1_or_1_nl});
  assign z_out = nl_z_out[31:0];
  assign fir_for_1_mux_14_nl = MUX_v_31_2_2((z_out[31:1]), iir_feedforward_1_31_1_sva,
      fsm_output[3]);
  assign fir_for_1_mux_15_nl = MUX_s_1_2_2((z_out[0]), iir_feedforward_1_0_sva, fsm_output[3]);
  assign fir_for_1_mux_16_nl = MUX_v_30_2_2((z_out_4[29:0]), (iir_for_1_1_mul_itm[31:2]),
      fsm_output[3]);
  assign fir_for_1_mux_17_nl = MUX_s_1_2_2((fir_delay_lane_2_sva[0]), (iir_for_1_1_mul_itm[1]),
      fsm_output[3]);
  assign fir_for_1_fir_for_1_and_1_nl = (iir_for_1_1_mul_itm[0]) & (fsm_output[3]);
  assign nl_z_out_1 = ({fir_for_1_mux_14_nl , fir_for_1_mux_15_nl}) + ({fir_for_1_mux_16_nl
      , fir_for_1_mux_17_nl , fir_for_1_fir_for_1_and_1_nl});
  assign z_out_1 = nl_z_out_1[31:0];
  assign fir_for_1_mux_18_nl = MUX_v_32_2_2(input_rsci_idat, iir_feedback_1_sva,
      fsm_output[3]);
  assign iir_for_2_1_iir_for_2_and_1_nl = MUX_v_32_2_2(32'b00000000000000000000000000000000,
      z_out_4, iir_for_2_i_2_1_sva_0);
  assign fir_for_1_mux_19_nl = MUX_v_32_2_2((~ fir_delay_lane_1_sva), iir_for_2_1_iir_for_2_and_1_nl,
      fsm_output[3]);
  assign nl_z_out_2 = fir_for_1_mux_18_nl + fir_for_1_mux_19_nl;
  assign z_out_2 = nl_z_out_2[31:0];
  assign fir_for_1_mux_20_nl = MUX_v_32_2_2(z_out_1, z_out_2, fsm_output[3]);
  assign iir_for_2_not_5_nl = ~ iir_for_2_i_2_1_sva_0;
  assign iir_for_2_2_iir_for_2_and_1_nl = MUX_v_32_2_2(32'b00000000000000000000000000000000,
      iir_output_delay_lane_1_sva, iir_for_2_not_5_nl);
  assign fir_for_1_mux_21_nl = MUX_v_32_2_2(z_out_2, iir_for_2_2_iir_for_2_and_1_nl,
      fsm_output[3]);
  assign nl_z_out_3 = fir_for_1_mux_20_nl + fir_for_1_mux_21_nl;
  assign z_out_3 = nl_z_out_3[31:0];
  assign iir_for_2_1_slc_iir_iir_for_2_mux_1_nl = MUX_v_32_3_2(iir_output_delay_lane_0_sva,
      iir_output_delay_lane_2_sva, iir_output_delay_lane_4_lpi_2, {iir_for_2_i_2_1_sva_1
      , iir_for_2_i_2_1_sva_0});
  assign fir_for_1_mux_22_nl = MUX_v_32_2_2((signext_32_30(fir_delay_lane_2_sva[30:1])),
      (~ iir_for_2_1_slc_iir_iir_for_2_mux_1_nl), fsm_output[3]);
  assign fir_for_1_mux_23_nl = MUX_v_30_2_2((fir_delay_lane_1_sva[29:0]), 30'b000000000000000000000000000001,
      fsm_output[3]);
  assign nl_z_out_4 = fir_for_1_mux_22_nl + conv_u2u_30_32(fir_for_1_mux_23_nl);
  assign z_out_4 = nl_z_out_4[31:0];

  function automatic [31:0] MUX1HOT_v_32_3_2;
    input [31:0] input_2;
    input [31:0] input_1;
    input [31:0] input_0;
    input [2:0] sel;
    reg [31:0] result;
  begin
    result = input_0 & {32{sel[0]}};
    result = result | (input_1 & {32{sel[1]}});
    result = result | (input_2 & {32{sel[2]}});
    MUX1HOT_v_32_3_2 = result;
  end
  endfunction


  function automatic [31:0] MUX1HOT_v_32_4_2;
    input [31:0] input_3;
    input [31:0] input_2;
    input [31:0] input_1;
    input [31:0] input_0;
    input [3:0] sel;
    reg [31:0] result;
  begin
    result = input_0 & {32{sel[0]}};
    result = result | (input_1 & {32{sel[1]}});
    result = result | (input_2 & {32{sel[2]}});
    result = result | (input_3 & {32{sel[3]}});
    MUX1HOT_v_32_4_2 = result;
  end
  endfunction


  function automatic  MUX_s_1_2_2;
    input  input_0;
    input  input_1;
    input  sel;
    reg  result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_s_1_2_2 = result;
  end
  endfunction


  function automatic [29:0] MUX_v_30_2_2;
    input [29:0] input_0;
    input [29:0] input_1;
    input  sel;
    reg [29:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_30_2_2 = result;
  end
  endfunction


  function automatic [30:0] MUX_v_31_2_2;
    input [30:0] input_0;
    input [30:0] input_1;
    input  sel;
    reg [30:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_31_2_2 = result;
  end
  endfunction


  function automatic [31:0] MUX_v_32_2_2;
    input [31:0] input_0;
    input [31:0] input_1;
    input  sel;
    reg [31:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_32_2_2 = result;
  end
  endfunction


  function automatic [31:0] MUX_v_32_3_2;
    input [31:0] input_0;
    input [31:0] input_1;
    input [31:0] input_2;
    input [1:0] sel;
    reg [31:0] result;
  begin
    case (sel)
      2'b00 : begin
        result = input_0;
      end
      2'b01 : begin
        result = input_1;
      end
      default : begin
        result = input_2;
      end
    endcase
    MUX_v_32_3_2 = result;
  end
  endfunction


  function automatic [31:0] signext_32_30;
    input [29:0] vector;
  begin
    signext_32_30= {{2{vector[29]}}, vector};
  end
  endfunction


  function automatic [2:0] conv_u2s_2_3 ;
    input [1:0]  vector ;
  begin
    conv_u2s_2_3 =  {1'b0, vector};
  end
  endfunction


  function automatic [31:0] conv_u2u_30_32 ;
    input [29:0]  vector ;
  begin
    conv_u2u_30_32 = {{2{1'b0}}, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    filter
// ------------------------------------------------------------------


module filter (
  clk, rst_n, input_rsc_dat, input_triosy_lz, fir_output_rsc_dat, fir_output_triosy_lz,
      iir_output_rsc_dat, iir_output_triosy_lz
);
  input clk;
  input rst_n;
  input [31:0] input_rsc_dat;
  output input_triosy_lz;
  output [31:0] fir_output_rsc_dat;
  output fir_output_triosy_lz;
  output [31:0] iir_output_rsc_dat;
  output iir_output_triosy_lz;



  // Interconnect Declarations for Component Instantiations 
  filter_core filter_core_inst (
      .clk(clk),
      .rst_n(rst_n),
      .input_rsc_dat(input_rsc_dat),
      .input_triosy_lz(input_triosy_lz),
      .fir_output_rsc_dat(fir_output_rsc_dat),
      .fir_output_triosy_lz(fir_output_triosy_lz),
      .iir_output_rsc_dat(iir_output_rsc_dat),
      .iir_output_triosy_lz(iir_output_triosy_lz)
    );
endmodule



