
//------> /eda/mentor/Siemens_EDA/Catapult_Synthesis_2023.1_2/Mgc_home/pkgs/siflibs/ccs_in_v1.v 
//------------------------------------------------------------------------------
// Catapult Synthesis - Sample I/O Port Library
//
// Copyright (c) 2003-2017 Mentor Graphics Corp.
//       All Rights Reserved
//
// This document may be used and distributed without restriction provided that
// this copyright statement is not removed from the file and that any derivative
// work contains this copyright notice.
//
// The design information contained in this file is intended to be an example
// of the functionality which the end user may study in preparation for creating
// their own custom interfaces. This design does not necessarily present a 
// complete implementation of the named protocol or standard.
//
//------------------------------------------------------------------------------


module ccs_in_v1 (idat, dat);

  parameter integer rscid = 1;
  parameter integer width = 8;

  output [width-1:0] idat;
  input  [width-1:0] dat;

  wire   [width-1:0] idat;

  assign idat = dat;

endmodule


//------> /eda/mentor/Siemens_EDA/Catapult_Synthesis_2023.1_2/Mgc_home/pkgs/siflibs/ccs_out_v1.v 
//------------------------------------------------------------------------------
// Catapult Synthesis - Sample I/O Port Library
//
// Copyright (c) 2003-2015 Mentor Graphics Corp.
//       All Rights Reserved
//
// This document may be used and distributed without restriction provided that
// this copyright statement is not removed from the file and that any derivative
// work contains this copyright notice.
//
// The design information contained in this file is intended to be an example
// of the functionality which the end user may study in preparation for creating
// their own custom interfaces. This design does not necessarily present a 
// complete implementation of the named protocol or standard.
//
//------------------------------------------------------------------------------

module ccs_out_v1 (dat, idat);

  parameter integer rscid = 1;
  parameter integer width = 8;

  output   [width-1:0] dat;
  input    [width-1:0] idat;

  wire     [width-1:0] dat;

  assign dat = idat;

endmodule




//------> /eda/mentor/Siemens_EDA/Catapult_Synthesis_2023.1_2/Mgc_home/pkgs/siflibs/mgc_io_sync_v2.v 
//------------------------------------------------------------------------------
// Catapult Synthesis - Sample I/O Port Library
//
// Copyright (c) 2003-2017 Mentor Graphics Corp.
//       All Rights Reserved
//
// This document may be used and distributed without restriction provided that
// this copyright statement is not removed from the file and that any derivative
// work contains this copyright notice.
//
// The design information contained in this file is intended to be an example
// of the functionality which the end user may study in preparation for creating
// their own custom interfaces. This design does not necessarily present a 
// complete implementation of the named protocol or standard.
//
//------------------------------------------------------------------------------


module mgc_io_sync_v2 (ld, lz);
    parameter valid = 0;

    input  ld;
    output lz;

    wire   lz;

    assign lz = ld;

endmodule


//------> ./rtl.v 
// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2023.1_2/1049935 Production Release
//  HLS Date:       Sat Jun 10 10:53:51 PDT 2023
// 
//  Generated by:   ajh9498@hansolo.poly.edu
//  Generated date: Fri Feb 28 18:18:54 2025
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    filter_core_core_fsm
//  FSM Module
// ------------------------------------------------------------------


module filter_core_core_fsm (
  clk, rst_n, fsm_output, shift_for_C_0_tr0, mac_for_C_0_tr0, shift_1_for_C_0_tr0
);
  input clk;
  input rst_n;
  output [7:0] fsm_output;
  reg [7:0] fsm_output;
  input shift_for_C_0_tr0;
  input mac_for_C_0_tr0;
  input shift_1_for_C_0_tr0;


  // FSM State Type Declaration for filter_core_core_fsm_1
  parameter
    main_C_0 = 3'd0,
    main_C_1 = 3'd1,
    shift_for_C_0 = 3'd2,
    mac_for_C_0 = 3'd3,
    main_C_2 = 3'd4,
    main_C_3 = 3'd5,
    shift_1_for_C_0 = 3'd6,
    main_C_4 = 3'd7;

  reg [2:0] state_var;
  reg [2:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : filter_core_core_fsm_1
    case (state_var)
      main_C_1 : begin
        fsm_output = 8'b00000010;
        state_var_NS = shift_for_C_0;
      end
      shift_for_C_0 : begin
        fsm_output = 8'b00000100;
        if ( shift_for_C_0_tr0 ) begin
          state_var_NS = mac_for_C_0;
        end
        else begin
          state_var_NS = shift_for_C_0;
        end
      end
      mac_for_C_0 : begin
        fsm_output = 8'b00001000;
        if ( mac_for_C_0_tr0 ) begin
          state_var_NS = main_C_2;
        end
        else begin
          state_var_NS = mac_for_C_0;
        end
      end
      main_C_2 : begin
        fsm_output = 8'b00010000;
        state_var_NS = main_C_3;
      end
      main_C_3 : begin
        fsm_output = 8'b00100000;
        state_var_NS = shift_1_for_C_0;
      end
      shift_1_for_C_0 : begin
        fsm_output = 8'b01000000;
        if ( shift_1_for_C_0_tr0 ) begin
          state_var_NS = main_C_4;
        end
        else begin
          state_var_NS = shift_1_for_C_0;
        end
      end
      main_C_4 : begin
        fsm_output = 8'b10000000;
        state_var_NS = main_C_0;
      end
      // main_C_0
      default : begin
        fsm_output = 8'b00000001;
        state_var_NS = main_C_1;
      end
    endcase
  end

  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      state_var <= main_C_0;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    filter_core
// ------------------------------------------------------------------


module filter_core (
  clk, rst_n, input_rsc_dat, input_triosy_lz, fir_output_rsc_dat, fir_output_triosy_lz,
      iir_output_rsc_dat, iir_output_triosy_lz
);
  input clk;
  input rst_n;
  input [31:0] input_rsc_dat;
  output input_triosy_lz;
  output [31:0] fir_output_rsc_dat;
  output fir_output_triosy_lz;
  output [31:0] iir_output_rsc_dat;
  output iir_output_triosy_lz;


  // Interconnect Declarations
  wire [31:0] input_rsci_idat;
  reg [31:0] fir_output_rsci_idat;
  wire [32:0] nl_fir_output_rsci_idat;
  reg [31:0] iir_output_rsci_idat;
  wire [7:0] fsm_output;
  wire mac_for_mac_for_nor_tmp;
  wire or_dcpl_6;
  wire or_dcpl_7;
  wire or_dcpl_8;
  wire or_dcpl_9;
  wire or_tmp_8;
  wire or_tmp_13;
  wire or_tmp_22;
  wire and_3_cse;
  wire and_55_cse;
  wire [1:0] shift_for_i_1_0_sva_2;
  wire [2:0] nl_shift_for_i_1_0_sva_2;
  reg reg_iir_output_triosy_obj_ld_cse;
  wire nor_5_seb;
  reg mac_1_for_i_2_0_sva_2;
  reg [1:0] mac_1_for_i_2_0_sva_1_0;
  wire [31:0] mac_1_for_mul_itm;
  wire signed [33:0] nl_mac_1_for_mul_itm;
  wire [31:0] mac_for_mul_itm;
  wire signed [34:0] nl_mac_for_mul_itm;
  wire [31:0] z_out;
  wire [32:0] nl_z_out;
  wire [31:0] z_out_1;
  wire [32:0] nl_z_out_1;
  reg [31:0] fir_delay_lane_2_sva;
  reg [31:0] fir_delay_lane_1_sva;
  reg [31:0] fir_delay_lane_0_sva;
  reg [31:0] iir_output_delay_lane_2_sva;
  reg [31:0] iir_output_delay_lane_1_sva;
  reg [31:0] iir_output_delay_lane_3_sva;
  reg [31:0] iir_output_delay_lane_0_sva;
  reg [31:0] iir_input_delay_lane_2_lpi_2;
  reg [31:0] iir_input_delay_lane_1_lpi_2;
  reg [31:0] iir_input_delay_lane_3_lpi_2;
  reg [31:0] iir_input_delay_lane_4_lpi_2;
  reg [31:0] iir_output_delay_lane_2_lpi_2;
  reg [31:0] iir_output_delay_lane_1_lpi_2;
  reg [31:0] iir_output_delay_lane_3_lpi_2;
  reg [31:0] iir_output_delay_lane_4_lpi_2;
  reg [31:0] input_sva;
  reg [2:0] mac_for_i_2_0_sva;
  reg [31:0] mac_1_result_sva;
  reg [31:0] iir_iir_acc_1_ncse_sva;
  wire [31:0] iir_output_delay_lane_1_sva_mx1;
  wire [31:0] iir_output_delay_lane_2_sva_mx1;
  wire [31:0] iir_output_delay_lane_3_sva_mx1;
  wire [2:0] mac_1_for_i_2_0_sva_2_1;
  wire [3:0] nl_mac_1_for_i_2_0_sva_2_1;
  wire [2:0] mac_for_i_2_0_sva_3;
  wire [3:0] nl_mac_for_i_2_0_sva_3;
  wire [31:0] shift_for_slc_iir_input_delay_lane_32_31_0_ctmp_sva_1;
  wire [31:0] shift_1_for_slc_iir_output_delay_lane_32_31_0_ctmp_sva_1;
  wire shift_for_conc_5_1;
  wire shift_for_acc_3_itm_2_1;

  wire[31:0] fir_acc_acc_6_nl;
  wire[32:0] nl_fir_acc_acc_6_nl;
  wire[31:0] iir_mux1h_nl;
  wire iir_or_1_nl;
  wire iir_not_1_nl;
  wire and_nl;
  wire nor_nl;
  wire nor_6_nl;
  wire[1:0] mac_for_i_mux_1_nl;
  wire or_58_nl;
  wire nor_7_nl;
  wire[31:0] mac_1_result_mux1h_2_nl;
  wire not_33_nl;
  wire[31:0] mac_1_for_mux_nl;
  wire mac_1_for_and_3_nl;
  wire mac_1_for_nor_nl;
  wire[31:0] mac_for_mux_nl;
  wire[1:0] mac_for_mux_1_nl;
  wire[2:0] shift_for_acc_3_nl;
  wire[3:0] nl_shift_for_acc_3_nl;
  wire[3:0] mac_for_acc_nl;
  wire[4:0] nl_mac_for_acc_nl;
  wire[3:0] mac_1_for_acc_nl;
  wire[4:0] nl_mac_1_for_acc_nl;
  wire[30:0] fir_acc_mux1h_2_nl;
  wire fir_acc_fir_acc_and_2_nl;
  wire fir_acc_mux_4_nl;
  wire[31:0] fir_acc_mux_5_nl;
  wire[30:0] fir_acc_mux_6_nl;
  wire[30:0] fir_acc_acc_9_nl;
  wire[31:0] nl_fir_acc_acc_9_nl;
  wire fir_acc_fir_acc_and_3_nl;

  // Interconnect Declarations for Component Instantiations 
  wire  nl_filter_core_core_fsm_inst_shift_for_C_0_tr0;
  assign nl_filter_core_core_fsm_inst_shift_for_C_0_tr0 = ~ shift_for_acc_3_itm_2_1;
  wire  nl_filter_core_core_fsm_inst_shift_1_for_C_0_tr0;
  assign nl_filter_core_core_fsm_inst_shift_1_for_C_0_tr0 = ~ shift_for_acc_3_itm_2_1;
  ccs_in_v1 #(.rscid(32'sd1),
  .width(32'sd32)) input_rsci (
      .dat(input_rsc_dat),
      .idat(input_rsci_idat)
    );
  ccs_out_v1 #(.rscid(32'sd2),
  .width(32'sd32)) fir_output_rsci (
      .idat(fir_output_rsci_idat),
      .dat(fir_output_rsc_dat)
    );
  ccs_out_v1 #(.rscid(32'sd3),
  .width(32'sd32)) iir_output_rsci (
      .idat(iir_output_rsci_idat),
      .dat(iir_output_rsc_dat)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) input_triosy_obj (
      .ld(reg_iir_output_triosy_obj_ld_cse),
      .lz(input_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) fir_output_triosy_obj (
      .ld(reg_iir_output_triosy_obj_ld_cse),
      .lz(fir_output_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) iir_output_triosy_obj (
      .ld(reg_iir_output_triosy_obj_ld_cse),
      .lz(iir_output_triosy_lz)
    );
  filter_core_core_fsm filter_core_core_fsm_inst (
      .clk(clk),
      .rst_n(rst_n),
      .fsm_output(fsm_output),
      .shift_for_C_0_tr0(nl_filter_core_core_fsm_inst_shift_for_C_0_tr0),
      .mac_for_C_0_tr0(mac_for_mac_for_nor_tmp),
      .shift_1_for_C_0_tr0(nl_filter_core_core_fsm_inst_shift_1_for_C_0_tr0)
    );
  assign nor_5_seb = ~((fsm_output[7]) | (fsm_output[0]) | (fsm_output[4]) | and_55_cse);
  assign iir_output_delay_lane_1_sva_mx1 = MUX_v_32_2_2(shift_1_for_slc_iir_output_delay_lane_32_31_0_ctmp_sva_1,
      iir_output_delay_lane_1_lpi_2, or_dcpl_6);
  assign iir_output_delay_lane_2_sva_mx1 = MUX_v_32_2_2(shift_1_for_slc_iir_output_delay_lane_32_31_0_ctmp_sva_1,
      iir_output_delay_lane_2_lpi_2, or_dcpl_7);
  assign iir_output_delay_lane_3_sva_mx1 = MUX_v_32_2_2(shift_1_for_slc_iir_output_delay_lane_32_31_0_ctmp_sva_1,
      iir_output_delay_lane_3_lpi_2, or_dcpl_8);
  assign mac_1_for_mux_nl = MUX_v_32_5_2(iir_output_delay_lane_0_sva, iir_output_delay_lane_1_sva,
      iir_output_delay_lane_2_sva, iir_output_delay_lane_3_sva, iir_output_delay_lane_4_lpi_2,
      {mac_1_for_i_2_0_sva_2 , mac_1_for_i_2_0_sva_1_0});
  assign mac_1_for_and_3_nl = (mac_1_for_i_2_0_sva_1_0[1]) & (~(mac_1_for_i_2_0_sva_2
      | (mac_1_for_i_2_0_sva_1_0[0])));
  assign mac_1_for_nor_nl = ~((~(mac_1_for_i_2_0_sva_2 | (mac_1_for_i_2_0_sva_1_0!=2'b00)))
      | ((mac_1_for_i_2_0_sva_1_0==2'b11) & (~ mac_1_for_i_2_0_sva_2)) | (mac_1_for_i_2_0_sva_2
      & (mac_1_for_i_2_0_sva_1_0==2'b00)));
  assign nl_mac_1_for_mul_itm = $signed(mac_1_for_mux_nl) * $signed(({mac_1_for_and_3_nl
      , mac_1_for_nor_nl}));
  assign mac_1_for_mul_itm = nl_mac_1_for_mul_itm[31:0];
  assign mac_for_mux_nl = MUX_v_32_5_2(input_sva, iir_input_delay_lane_1_lpi_2, iir_input_delay_lane_2_lpi_2,
      iir_input_delay_lane_3_lpi_2, iir_input_delay_lane_4_lpi_2, mac_for_i_2_0_sva);
  assign mac_for_mux_1_nl = MUX_v_2_5_2(2'b01, 2'b10, 2'b11, 2'b10, 2'b01, mac_for_i_2_0_sva);
  assign nl_mac_for_mul_itm = $signed(mac_for_mux_nl) * $signed(conv_u2s_2_3(mac_for_mux_1_nl));
  assign mac_for_mul_itm = nl_mac_for_mul_itm[31:0];
  assign nl_mac_1_for_i_2_0_sva_2_1 = ({mac_1_for_i_2_0_sva_2 , mac_1_for_i_2_0_sva_1_0})
      + 3'b001;
  assign mac_1_for_i_2_0_sva_2_1 = nl_mac_1_for_i_2_0_sva_2_1[2:0];
  assign nl_mac_for_i_2_0_sva_3 = mac_for_i_2_0_sva + 3'b001;
  assign mac_for_i_2_0_sva_3 = nl_mac_for_i_2_0_sva_3[2:0];
  assign nl_shift_for_i_1_0_sva_2 = mac_1_for_i_2_0_sva_1_0 + 2'b11;
  assign shift_for_i_1_0_sva_2 = nl_shift_for_i_1_0_sva_2[1:0];
  assign shift_for_slc_iir_input_delay_lane_32_31_0_ctmp_sva_1 = MUX_v_32_4_2(iir_input_delay_lane_1_lpi_2,
      iir_iir_acc_1_ncse_sva, iir_input_delay_lane_3_lpi_2, iir_input_delay_lane_2_lpi_2,
      {shift_for_conc_5_1 , (mac_1_for_i_2_0_sva_1_0[0])});
  assign shift_1_for_slc_iir_output_delay_lane_32_31_0_ctmp_sva_1 = MUX_v_32_4_2(iir_output_delay_lane_1_lpi_2,
      iir_output_delay_lane_0_sva, iir_output_delay_lane_3_lpi_2, iir_output_delay_lane_2_lpi_2,
      {shift_for_conc_5_1 , (mac_1_for_i_2_0_sva_1_0[0])});
  assign nl_shift_for_acc_3_nl = ({1'b1 , (~ shift_for_i_1_0_sva_2)}) + 3'b001;
  assign shift_for_acc_3_nl = nl_shift_for_acc_3_nl[2:0];
  assign shift_for_acc_3_itm_2_1 = readslicef_3_1_2(shift_for_acc_3_nl);
  assign shift_for_conc_5_1 = ~((mac_1_for_i_2_0_sva_1_0[0]) ^ (mac_1_for_i_2_0_sva_1_0[1]));
  assign nl_mac_for_acc_nl = conv_u2s_3_4(mac_for_i_2_0_sva_3) + 4'b1011;
  assign mac_for_acc_nl = nl_mac_for_acc_nl[3:0];
  assign nl_mac_1_for_acc_nl = conv_u2s_3_4(mac_1_for_i_2_0_sva_2_1) + 4'b1011;
  assign mac_1_for_acc_nl = nl_mac_1_for_acc_nl[3:0];
  assign mac_for_mac_for_nor_tmp = ~((readslicef_4_1_3(mac_for_acc_nl)) | (readslicef_4_1_3(mac_1_for_acc_nl)));
  assign and_3_cse = (~ mac_for_mac_for_nor_tmp) & (fsm_output[3]);
  assign or_dcpl_6 = (mac_1_for_i_2_0_sva_1_0!=2'b01);
  assign or_dcpl_7 = (mac_1_for_i_2_0_sva_1_0!=2'b10);
  assign or_dcpl_8 = ~((mac_1_for_i_2_0_sva_1_0==2'b11));
  assign or_dcpl_9 = (mac_1_for_i_2_0_sva_1_0!=2'b00);
  assign or_tmp_8 = (~ (fsm_output[6])) | shift_for_acc_3_itm_2_1;
  assign or_tmp_13 = (~ shift_for_acc_3_itm_2_1) & (fsm_output[6]);
  assign and_55_cse = (~ shift_for_acc_3_itm_2_1) & (fsm_output[2]);
  assign or_tmp_22 = mac_for_mac_for_nor_tmp & (fsm_output[3]);
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      fir_output_rsci_idat <= 32'b00000000000000000000000000000000;
    end
    else if ( fsm_output[0] ) begin
      fir_output_rsci_idat <= nl_fir_output_rsci_idat[31:0];
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_rsci_idat <= 32'b00000000000000000000000000000000;
    end
    else if ( fsm_output[4] ) begin
      iir_output_rsci_idat <= z_out;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_0_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_8 ) begin
      iir_output_delay_lane_0_sva <= iir_iir_acc_1_ncse_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_1_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( fsm_output[6] ) begin
      iir_output_delay_lane_1_sva <= iir_output_delay_lane_1_sva_mx1;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_2_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( fsm_output[6] ) begin
      iir_output_delay_lane_2_sva <= iir_output_delay_lane_2_sva_mx1;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_3_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( fsm_output[6] ) begin
      iir_output_delay_lane_3_sva <= iir_output_delay_lane_3_sva_mx1;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      input_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( (fsm_output[7]) | (fsm_output[0]) ) begin
      input_sva <= input_rsci_idat;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      reg_iir_output_triosy_obj_ld_cse <= 1'b0;
      mac_1_for_i_2_0_sva_2 <= 1'b0;
      mac_1_for_i_2_0_sva_1_0 <= 2'b00;
      mac_for_i_2_0_sva <= 3'b000;
    end
    else begin
      reg_iir_output_triosy_obj_ld_cse <= or_tmp_13;
      mac_1_for_i_2_0_sva_2 <= (mac_1_for_i_2_0_sva_2_1[2]) & nor_5_seb;
      mac_1_for_i_2_0_sva_1_0 <= MUX_v_2_2_2(2'b00, mac_for_i_mux_1_nl, nor_7_nl);
      mac_for_i_2_0_sva <= MUX_v_3_2_2(3'b000, mac_for_i_2_0_sva_3, (fsm_output[3]));
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      fir_delay_lane_0_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_8 ) begin
      fir_delay_lane_0_sva <= input_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      fir_delay_lane_2_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_8 ) begin
      fir_delay_lane_2_sva <= fir_delay_lane_1_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      fir_delay_lane_1_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_8 ) begin
      fir_delay_lane_1_sva <= fir_delay_lane_0_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_input_delay_lane_1_lpi_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( ~((~ (fsm_output[2])) | or_dcpl_6) ) begin
      iir_input_delay_lane_1_lpi_2 <= shift_for_slc_iir_input_delay_lane_32_31_0_ctmp_sva_1;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_input_delay_lane_2_lpi_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( ~((~ (fsm_output[2])) | or_dcpl_7) ) begin
      iir_input_delay_lane_2_lpi_2 <= shift_for_slc_iir_input_delay_lane_32_31_0_ctmp_sva_1;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_input_delay_lane_3_lpi_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( ~((~ (fsm_output[2])) | or_dcpl_8) ) begin
      iir_input_delay_lane_3_lpi_2 <= shift_for_slc_iir_input_delay_lane_32_31_0_ctmp_sva_1;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_4_lpi_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( (~ or_dcpl_9) & (fsm_output[6]) ) begin
      iir_output_delay_lane_4_lpi_2 <= shift_1_for_slc_iir_output_delay_lane_32_31_0_ctmp_sva_1;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_iir_acc_1_ncse_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( and_55_cse | or_tmp_22 | and_3_cse | (fsm_output[4]) | or_tmp_13 )
        begin
      iir_iir_acc_1_ncse_sva <= MUX_v_32_2_2(32'b00000000000000000000000000000000,
          iir_mux1h_nl, iir_not_1_nl);
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_input_delay_lane_4_lpi_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( ~(or_dcpl_9 | (fsm_output[3])) ) begin
      iir_input_delay_lane_4_lpi_2 <= shift_for_slc_iir_input_delay_lane_32_31_0_ctmp_sva_1;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_3_lpi_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( MUX_s_1_2_2((fsm_output[1]), and_nl, fsm_output[6]) ) begin
      iir_output_delay_lane_3_lpi_2 <= MUX_v_32_2_2(iir_output_delay_lane_3_sva,
          iir_output_delay_lane_3_sva_mx1, fsm_output[6]);
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_1_lpi_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( MUX_s_1_2_2((fsm_output[1]), nor_nl, fsm_output[6]) ) begin
      iir_output_delay_lane_1_lpi_2 <= MUX_v_32_2_2(iir_output_delay_lane_1_sva,
          iir_output_delay_lane_1_sva_mx1, fsm_output[6]);
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_2_lpi_2 <= 32'b00000000000000000000000000000000;
    end
    else if ( MUX_s_1_2_2((fsm_output[1]), nor_6_nl, fsm_output[6]) ) begin
      iir_output_delay_lane_2_lpi_2 <= MUX_v_32_2_2(iir_output_delay_lane_2_sva,
          iir_output_delay_lane_2_sva_mx1, fsm_output[6]);
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      mac_1_result_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( (fsm_output[2]) | (fsm_output[6]) | and_3_cse | or_tmp_22 ) begin
      mac_1_result_sva <= MUX_v_32_2_2(32'b00000000000000000000000000000000, mac_1_result_mux1h_2_nl,
          not_33_nl);
    end
  end
  assign nl_fir_acc_acc_6_nl = input_rsci_idat + fir_delay_lane_1_sva;
  assign fir_acc_acc_6_nl = nl_fir_acc_acc_6_nl[31:0];
  assign nl_fir_output_rsci_idat  = z_out_1 + fir_acc_acc_6_nl;
  assign or_58_nl = (fsm_output[1]) | (fsm_output[5]) | (fsm_output[6]) | (shift_for_acc_3_itm_2_1
      & (fsm_output[2]));
  assign mac_for_i_mux_1_nl = MUX_v_2_2_2((mac_1_for_i_2_0_sva_2_1[1:0]), shift_for_i_1_0_sva_2,
      or_58_nl);
  assign nor_7_nl = ~((~ nor_5_seb) | (fsm_output[1]) | (fsm_output[5]));
  assign iir_or_1_nl = or_tmp_22 | (fsm_output[4]);
  assign iir_mux1h_nl = MUX1HOT_v_32_3_2(z_out, z_out_1, input_sva, {iir_or_1_nl
      , and_3_cse , or_tmp_13});
  assign iir_not_1_nl = ~ and_55_cse;
  assign and_nl = (mac_1_for_i_2_0_sva_1_0==2'b11);
  assign nor_nl = ~((mac_1_for_i_2_0_sva_1_0!=2'b01));
  assign nor_6_nl = ~((mac_1_for_i_2_0_sva_1_0!=2'b10));
  assign mac_1_result_mux1h_2_nl = MUX1HOT_v_32_3_2(z_out, z_out_1, fir_delay_lane_2_sva,
      {and_3_cse , or_tmp_22 , (fsm_output[6])});
  assign not_33_nl = ~ (fsm_output[2]);
  assign fir_acc_mux1h_2_nl = MUX1HOT_v_31_3_2((fir_delay_lane_0_sva[30:0]), (iir_iir_acc_1_ncse_sva[31:1]),
      (mac_1_for_mul_itm[31:1]), {(fsm_output[0]) , (fsm_output[4]) , (fsm_output[3])});
  assign fir_acc_mux_4_nl = MUX_s_1_2_2((iir_iir_acc_1_ncse_sva[0]), (mac_1_for_mul_itm[0]),
      fsm_output[3]);
  assign fir_acc_fir_acc_and_2_nl = fir_acc_mux_4_nl & (~ (fsm_output[0]));
  assign nl_z_out = mac_1_result_sva + ({fir_acc_mux1h_2_nl , fir_acc_fir_acc_and_2_nl});
  assign z_out = nl_z_out[31:0];
  assign fir_acc_mux_5_nl = MUX_v_32_2_2(z_out, iir_iir_acc_1_ncse_sva, fsm_output[3]);
  assign nl_fir_acc_acc_9_nl = (fir_delay_lane_2_sva[30:0]) + (fir_delay_lane_1_sva[30:0]);
  assign fir_acc_acc_9_nl = nl_fir_acc_acc_9_nl[30:0];
  assign fir_acc_mux_6_nl = MUX_v_31_2_2(fir_acc_acc_9_nl, (mac_for_mul_itm[31:1]),
      fsm_output[3]);
  assign fir_acc_fir_acc_and_3_nl = (mac_for_mul_itm[0]) & (fsm_output[3]);
  assign nl_z_out_1 = fir_acc_mux_5_nl + ({fir_acc_mux_6_nl , fir_acc_fir_acc_and_3_nl});
  assign z_out_1 = nl_z_out_1[31:0];

  function automatic [30:0] MUX1HOT_v_31_3_2;
    input [30:0] input_2;
    input [30:0] input_1;
    input [30:0] input_0;
    input [2:0] sel;
    reg [30:0] result;
  begin
    result = input_0 & {31{sel[0]}};
    result = result | (input_1 & {31{sel[1]}});
    result = result | (input_2 & {31{sel[2]}});
    MUX1HOT_v_31_3_2 = result;
  end
  endfunction


  function automatic [31:0] MUX1HOT_v_32_3_2;
    input [31:0] input_2;
    input [31:0] input_1;
    input [31:0] input_0;
    input [2:0] sel;
    reg [31:0] result;
  begin
    result = input_0 & {32{sel[0]}};
    result = result | (input_1 & {32{sel[1]}});
    result = result | (input_2 & {32{sel[2]}});
    MUX1HOT_v_32_3_2 = result;
  end
  endfunction


  function automatic  MUX_s_1_2_2;
    input  input_0;
    input  input_1;
    input  sel;
    reg  result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_s_1_2_2 = result;
  end
  endfunction


  function automatic [1:0] MUX_v_2_2_2;
    input [1:0] input_0;
    input [1:0] input_1;
    input  sel;
    reg [1:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_2_2_2 = result;
  end
  endfunction


  function automatic [1:0] MUX_v_2_5_2;
    input [1:0] input_0;
    input [1:0] input_1;
    input [1:0] input_2;
    input [1:0] input_3;
    input [1:0] input_4;
    input [2:0] sel;
    reg [1:0] result;
  begin
    case (sel)
      3'b000 : begin
        result = input_0;
      end
      3'b001 : begin
        result = input_1;
      end
      3'b010 : begin
        result = input_2;
      end
      3'b011 : begin
        result = input_3;
      end
      default : begin
        result = input_4;
      end
    endcase
    MUX_v_2_5_2 = result;
  end
  endfunction


  function automatic [30:0] MUX_v_31_2_2;
    input [30:0] input_0;
    input [30:0] input_1;
    input  sel;
    reg [30:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_31_2_2 = result;
  end
  endfunction


  function automatic [31:0] MUX_v_32_2_2;
    input [31:0] input_0;
    input [31:0] input_1;
    input  sel;
    reg [31:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_32_2_2 = result;
  end
  endfunction


  function automatic [31:0] MUX_v_32_4_2;
    input [31:0] input_0;
    input [31:0] input_1;
    input [31:0] input_2;
    input [31:0] input_3;
    input [1:0] sel;
    reg [31:0] result;
  begin
    case (sel)
      2'b00 : begin
        result = input_0;
      end
      2'b01 : begin
        result = input_1;
      end
      2'b10 : begin
        result = input_2;
      end
      default : begin
        result = input_3;
      end
    endcase
    MUX_v_32_4_2 = result;
  end
  endfunction


  function automatic [31:0] MUX_v_32_5_2;
    input [31:0] input_0;
    input [31:0] input_1;
    input [31:0] input_2;
    input [31:0] input_3;
    input [31:0] input_4;
    input [2:0] sel;
    reg [31:0] result;
  begin
    case (sel)
      3'b000 : begin
        result = input_0;
      end
      3'b001 : begin
        result = input_1;
      end
      3'b010 : begin
        result = input_2;
      end
      3'b011 : begin
        result = input_3;
      end
      default : begin
        result = input_4;
      end
    endcase
    MUX_v_32_5_2 = result;
  end
  endfunction


  function automatic [2:0] MUX_v_3_2_2;
    input [2:0] input_0;
    input [2:0] input_1;
    input  sel;
    reg [2:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_3_2_2 = result;
  end
  endfunction


  function automatic [0:0] readslicef_3_1_2;
    input [2:0] vector;
    reg [2:0] tmp;
  begin
    tmp = vector >> 2;
    readslicef_3_1_2 = tmp[0:0];
  end
  endfunction


  function automatic [0:0] readslicef_4_1_3;
    input [3:0] vector;
    reg [3:0] tmp;
  begin
    tmp = vector >> 3;
    readslicef_4_1_3 = tmp[0:0];
  end
  endfunction


  function automatic [2:0] conv_u2s_2_3 ;
    input [1:0]  vector ;
  begin
    conv_u2s_2_3 =  {1'b0, vector};
  end
  endfunction


  function automatic [3:0] conv_u2s_3_4 ;
    input [2:0]  vector ;
  begin
    conv_u2s_3_4 =  {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    filter
// ------------------------------------------------------------------


module filter (
  clk, rst_n, input_rsc_dat, input_triosy_lz, fir_output_rsc_dat, fir_output_triosy_lz,
      iir_output_rsc_dat, iir_output_triosy_lz
);
  input clk;
  input rst_n;
  input [31:0] input_rsc_dat;
  output input_triosy_lz;
  output [31:0] fir_output_rsc_dat;
  output fir_output_triosy_lz;
  output [31:0] iir_output_rsc_dat;
  output iir_output_triosy_lz;



  // Interconnect Declarations for Component Instantiations 
  filter_core filter_core_inst (
      .clk(clk),
      .rst_n(rst_n),
      .input_rsc_dat(input_rsc_dat),
      .input_triosy_lz(input_triosy_lz),
      .fir_output_rsc_dat(fir_output_rsc_dat),
      .fir_output_triosy_lz(fir_output_triosy_lz),
      .iir_output_rsc_dat(iir_output_rsc_dat),
      .iir_output_triosy_lz(iir_output_triosy_lz)
    );
endmodule



