directive set /filter/filter:core/core/fir:delay_lane(0).sva REGISTER_NAME fir:delay_lane(0).sva
directive set /filter/filter:core/core/fir:delay_lane(1).sva#1 REGISTER_NAME fir:delay_lane(0).sva
directive set /filter/filter:core/core/fir:delay_lane(2).sva REGISTER_NAME fir:delay_lane(2).sva
directive set /filter/filter:core/core/fir:delay_lane(3).sva#1 REGISTER_NAME fir:delay_lane(2).sva
directive set /filter/filter:core/core/fir:delay_lane(1).sva REGISTER_NAME fir:delay_lane(1).sva
directive set /filter/filter:core/core/fir:delay_lane(2).sva#1 REGISTER_NAME fir:delay_lane(1).sva
directive set /filter/filter:core/core/iir:input_delay_lane(4).lpi#2 REGISTER_NAME iir:input_delay_lane(4).lpi#2
directive set /filter/filter:core/core/iir:input_delay_lane(4).sva#1 REGISTER_NAME iir:input_delay_lane(4).lpi#2
directive set /filter/filter:core/core/iir:input_delay_lane(3).lpi#2 REGISTER_NAME iir:input_delay_lane(3).lpi#2
directive set /filter/filter:core/core/iir:input_delay_lane(3).sva REGISTER_NAME iir:input_delay_lane(3).lpi#2
directive set /filter/filter:core/core/iir:input_delay_lane(3).sva#1 REGISTER_NAME iir:input_delay_lane(3).lpi#2
directive set /filter/filter:core/core/iir:input_delay_lane(1).lpi#2 REGISTER_NAME iir:input_delay_lane(1).lpi#2
directive set /filter/filter:core/core/iir:input_delay_lane(1).sva REGISTER_NAME iir:input_delay_lane(1).lpi#2
directive set /filter/filter:core/core/iir:input_delay_lane(1).sva#1 REGISTER_NAME iir:input_delay_lane(1).lpi#2
directive set /filter/filter:core/core/iir:input_delay_lane(2).lpi#2 REGISTER_NAME iir:input_delay_lane(2).lpi#2
directive set /filter/filter:core/core/iir:input_delay_lane(2).sva REGISTER_NAME iir:input_delay_lane(2).lpi#2
directive set /filter/filter:core/core/iir:input_delay_lane(2).sva#1 REGISTER_NAME iir:input_delay_lane(2).lpi#2
directive set /filter/filter:core/core/mac#1:for:i(2:0).sva REGISTER_NAME mac#1:for:i(2:0).sva
directive set /filter/filter:core/core/shift#1:for:i(1:0).sva REGISTER_NAME mac#1:for:i(2:0).sva
directive set /filter/filter:core/core/shift:for:i(1:0).sva REGISTER_NAME mac#1:for:i(2:0).sva
directive set /filter/filter:core/core/mac#1:result.sva REGISTER_NAME mac#1:result.sva
directive set /filter/filter:core/core/mac:result.sva#1 REGISTER_NAME mac#1:result.sva
directive set /filter/filter:core/core/fir:delay_lane(3).sva REGISTER_NAME mac#1:result.sva
directive set /filter/filter:core/core/iir:iir:acc#1.ncse.sva REGISTER_NAME iir:iir:acc#1.ncse.sva
directive set /filter/filter:core/core/iir:input_delay_lane(0).sva REGISTER_NAME iir:iir:acc#1.ncse.sva
directive set /filter/filter:core/core/mac#1:result.sva#1 REGISTER_NAME iir:iir:acc#1.ncse.sva
directive set /filter/filter:core/core/mac:result.sva REGISTER_NAME iir:iir:acc#1.ncse.sva
directive set /filter/filter:core/core/iir:output_delay_lane(4).lpi#2 REGISTER_NAME iir:output_delay_lane(4).lpi#2
directive set /filter/filter:core/core/iir:output_delay_lane(4).sva REGISTER_NAME iir:output_delay_lane(4).lpi#2
