// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2023.1_2/1049935 Production Release
//  HLS Date:       Sat Jun 10 10:53:51 PDT 2023
// 
//  Generated by:   ajh9498@hansolo.poly.edu
//  Generated date: Fri Feb 28 20:19:08 2025
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    filter_core_core_fsm
//  FSM Module
// ------------------------------------------------------------------


module filter_core_core_fsm (
  clk, rst_n, fsm_output, mac_for_C_1_tr0
);
  input clk;
  input rst_n;
  output [4:0] fsm_output;
  reg [4:0] fsm_output;
  input mac_for_C_1_tr0;


  // FSM State Type Declaration for filter_core_core_fsm_1
  parameter
    main_C_0 = 3'd0,
    mac_for_C_0 = 3'd1,
    mac_for_C_1 = 3'd2,
    main_C_1 = 3'd3,
    main_C_2 = 3'd4;

  reg [2:0] state_var;
  reg [2:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : filter_core_core_fsm_1
    case (state_var)
      mac_for_C_0 : begin
        fsm_output = 5'b00010;
        state_var_NS = mac_for_C_1;
      end
      mac_for_C_1 : begin
        fsm_output = 5'b00100;
        if ( mac_for_C_1_tr0 ) begin
          state_var_NS = main_C_1;
        end
        else begin
          state_var_NS = mac_for_C_0;
        end
      end
      main_C_1 : begin
        fsm_output = 5'b01000;
        state_var_NS = main_C_2;
      end
      main_C_2 : begin
        fsm_output = 5'b10000;
        state_var_NS = main_C_0;
      end
      // main_C_0
      default : begin
        fsm_output = 5'b00001;
        state_var_NS = mac_for_C_0;
      end
    endcase
  end

  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      state_var <= main_C_0;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    filter_core
// ------------------------------------------------------------------


module filter_core (
  clk, rst_n, input_rsc_dat, input_triosy_lz, fir_output_rsc_dat, fir_output_triosy_lz,
      iir_output_rsc_dat, iir_output_triosy_lz
);
  input clk;
  input rst_n;
  input [31:0] input_rsc_dat;
  output input_triosy_lz;
  output [31:0] fir_output_rsc_dat;
  output fir_output_triosy_lz;
  output [31:0] iir_output_rsc_dat;
  output iir_output_triosy_lz;


  // Interconnect Declarations
  wire [31:0] input_rsci_idat;
  reg [31:0] fir_output_rsci_idat;
  reg iir_output_triosy_obj_ld;
  wire [4:0] fsm_output;
  wire or_tmp_21;
  wire or_tmp_22;
  wire or_tmp_32;
  wire or_tmp_39;
  reg mac_for_mac_for_nor_itm;
  reg [2:0] mac_2_for_i_2_0_sva;
  wire mac_2_result_or_cse;
  reg reg_fir_output_triosy_obj_ld_cse;
  wire mac_2_for_if_and_3_itm;
  wire [31:0] z_out;
  wire [32:0] nl_z_out;
  wire [31:0] z_out_1;
  wire [32:0] nl_z_out_1;
  wire [31:0] z_out_2;
  wire [33:0] nl_z_out_2;
  reg [31:0] iir_output_delay_lane_2_sva;
  reg [31:0] iir_output_delay_lane_1_sva;
  reg [31:0] iir_output_delay_lane_3_sva;
  reg [31:0] iir_output_delay_lane_4_sva;
  reg [31:0] input_sva;
  reg [31:0] mac_result_sva;
  reg [2:0] mac_for_i_2_0_sva;
  reg [31:0] iir_input_delay_lane_3_sva_1;
  reg [31:0] iir_input_delay_lane_2_sva_1;
  reg [31:0] iir_input_delay_lane_1_sva_1;
  reg [31:0] mac_1_result_sva;
  reg [2:0] mac_1_for_i_2_0_sva;
  reg [31:0] mac_2_result_sva;
  reg [31:0] mac_for_if_mux_itm;
  reg [1:0] mac_for_if_mux_1_itm;
  wire [2:0] mac_2_for_i_2_0_sva_2;
  wire [3:0] nl_mac_2_for_i_2_0_sva_2;
  wire [2:0] mac_1_for_i_2_0_sva_2;
  wire [3:0] nl_mac_1_for_i_2_0_sva_2;
  wire [2:0] mac_for_i_2_0_sva_2;
  wire [3:0] nl_mac_for_i_2_0_sva_2;
  wire [31:0] fir_fir_and_cse;
  reg [31:0] reg_iir_output_rsci_idat_cse;
  reg [31:0] reg_iir_input_delay_lane_0_cse;
  reg [31:0] reg_iir_input_delay_lane_1_cse;
  wire mac_1_for_if_mac_1_for_if_nor_1_cse;
  wire mac_1_for_if_and_2_cse;
  wire mac_1_for_if_and_4_cse;
  wire mac_1_for_if_and_3_cse;
  wire mac_1_for_if_and_1_cse;
  reg [31:0] reg_iir_input_delay_lane_2_cse;
  reg [31:0] reg_iir_input_delay_lane_3_cse;

  wire mac_result_not_1_nl;
  wire not_25_nl;
  wire not_26_nl;
  wire mac_1_result_not_1_nl;
  wire not_27_nl;
  wire[3:0] mac_for_acc_nl;
  wire[4:0] nl_mac_for_acc_nl;
  wire[3:0] mac_1_for_acc_nl;
  wire[4:0] nl_mac_1_for_acc_nl;
  wire[3:0] mac_2_for_acc_nl;
  wire[4:0] nl_mac_2_for_acc_nl;
  wire[31:0] mac_2_for_if_mux_3_nl;
  wire[31:0] mac_2_for_if_mux_4_nl;
  wire[31:0] mac_2_for_if_mul_1_nl;
  wire signed [33:0] nl_mac_2_for_if_mul_1_nl;
  wire[31:0] mac_2_for_if_mux_5_nl;
  wire mac_2_for_if_or_2_nl;
  wire[31:0] mac_1_for_if_mux_5_nl;
  wire[1:0] mac_1_for_if_mac_1_for_if_or_1_nl;
  wire[1:0] mac_1_for_if_mux1h_1_nl;
  wire mac_1_for_if_or_2_nl;
  wire mac_1_for_if_or_3_nl;
  wire[31:0] mac_1_for_if_mac_1_for_if_mux1h_1_nl;

  // Interconnect Declarations for Component Instantiations 
  ccs_in_v1 #(.rscid(32'sd1),
  .width(32'sd32)) input_rsci (
      .dat(input_rsc_dat),
      .idat(input_rsci_idat)
    );
  ccs_out_v1 #(.rscid(32'sd2),
  .width(32'sd32)) fir_output_rsci (
      .idat(fir_output_rsci_idat),
      .dat(fir_output_rsc_dat)
    );
  ccs_out_v1 #(.rscid(32'sd3),
  .width(32'sd32)) iir_output_rsci (
      .idat(reg_iir_output_rsci_idat_cse),
      .dat(iir_output_rsc_dat)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) input_triosy_obj (
      .ld(reg_fir_output_triosy_obj_ld_cse),
      .lz(input_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) fir_output_triosy_obj (
      .ld(reg_fir_output_triosy_obj_ld_cse),
      .lz(fir_output_triosy_lz)
    );
  mgc_io_sync_v2 #(.valid(32'sd0)) iir_output_triosy_obj (
      .ld(iir_output_triosy_obj_ld),
      .lz(iir_output_triosy_lz)
    );
  filter_core_core_fsm filter_core_core_fsm_inst (
      .clk(clk),
      .rst_n(rst_n),
      .fsm_output(fsm_output),
      .mac_for_C_1_tr0(mac_for_mac_for_nor_itm)
    );
  assign mac_result_not_1_nl = ~ (fsm_output[0]);
  assign fir_fir_and_cse = MUX_v_32_2_2(32'b00000000000000000000000000000000, z_out,
      mac_result_not_1_nl);
  assign mac_2_result_or_cse = (fsm_output[1:0]!=2'b00);
  assign mac_2_for_if_and_3_itm = (mac_2_for_i_2_0_sva==3'b010);
  assign nl_mac_2_for_i_2_0_sva_2 = mac_2_for_i_2_0_sva + 3'b001;
  assign mac_2_for_i_2_0_sva_2 = nl_mac_2_for_i_2_0_sva_2[2:0];
  assign nl_mac_1_for_i_2_0_sva_2 = mac_1_for_i_2_0_sva + 3'b001;
  assign mac_1_for_i_2_0_sva_2 = nl_mac_1_for_i_2_0_sva_2[2:0];
  assign nl_mac_for_i_2_0_sva_2 = mac_for_i_2_0_sva + 3'b001;
  assign mac_for_i_2_0_sva_2 = nl_mac_for_i_2_0_sva_2[2:0];
  assign or_tmp_21 = ~((fsm_output[2]) & mac_for_mac_for_nor_itm);
  assign or_tmp_22 = ~((fsm_output[2:1]!=2'b00));
  assign or_tmp_32 = mac_for_mac_for_nor_itm & (fsm_output[2]);
  assign or_tmp_39 = (fsm_output[2:1]!=2'b00);
  assign mac_1_for_if_mac_1_for_if_nor_1_cse = ~((mac_1_for_i_2_0_sva!=3'b000) |
      (fsm_output[2]));
  assign mac_1_for_if_and_2_cse = (mac_1_for_i_2_0_sva==3'b001) & (~ (fsm_output[2]));
  assign mac_1_for_if_and_4_cse = (mac_1_for_i_2_0_sva==3'b010) & (~ (fsm_output[2]));
  assign mac_1_for_if_and_3_cse = (mac_1_for_i_2_0_sva==3'b011) & (~ (fsm_output[2]));
  assign mac_1_for_if_and_1_cse = (mac_1_for_i_2_0_sva==3'b100) & (~ (fsm_output[2]));
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      reg_iir_output_rsci_idat_cse <= 32'b00000000000000000000000000000000;
    end
    else if ( fsm_output[3] ) begin
      reg_iir_output_rsci_idat_cse <= z_out_1;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      mac_result_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( (fsm_output[0]) | (fsm_output[2]) ) begin
      mac_result_sva <= fir_fir_and_cse;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      fir_output_rsci_idat <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_21 ) begin
      fir_output_rsci_idat <= z_out;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      mac_2_for_i_2_0_sva <= 3'b000;
    end
    else if ( ~ (fsm_output[2]) ) begin
      mac_2_for_i_2_0_sva <= MUX_v_3_2_2(3'b000, mac_2_for_i_2_0_sva_2, not_25_nl);
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      mac_2_result_sva <= 32'b00000000000000000000000000000000;
      mac_1_result_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( mac_2_result_or_cse ) begin
      mac_2_result_sva <= fir_fir_and_cse;
      mac_1_result_sva <= MUX_v_32_2_2(32'b00000000000000000000000000000000, z_out_1,
          mac_1_result_not_1_nl);
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_1_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_21 ) begin
      iir_output_delay_lane_1_sva <= reg_iir_output_rsci_idat_cse;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_2_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_21 ) begin
      iir_output_delay_lane_2_sva <= iir_output_delay_lane_1_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_3_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_21 ) begin
      iir_output_delay_lane_3_sva <= iir_output_delay_lane_2_sva;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_delay_lane_4_sva <= 32'b00000000000000000000000000000000;
      reg_iir_input_delay_lane_0_cse <= 32'b00000000000000000000000000000000;
      reg_iir_input_delay_lane_1_cse <= 32'b00000000000000000000000000000000;
      reg_iir_input_delay_lane_2_cse <= 32'b00000000000000000000000000000000;
      reg_iir_input_delay_lane_3_cse <= 32'b00000000000000000000000000000000;
    end
    else if ( or_tmp_32 ) begin
      iir_output_delay_lane_4_sva <= iir_output_delay_lane_3_sva;
      reg_iir_input_delay_lane_0_cse <= input_sva;
      reg_iir_input_delay_lane_1_cse <= iir_input_delay_lane_1_sva_1;
      reg_iir_input_delay_lane_2_cse <= iir_input_delay_lane_2_sva_1;
      reg_iir_input_delay_lane_3_cse <= iir_input_delay_lane_3_sva_1;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      mac_1_for_i_2_0_sva <= 3'b000;
    end
    else if ( ~ (fsm_output[2]) ) begin
      mac_1_for_i_2_0_sva <= MUX_v_3_2_2(3'b000, mac_1_for_i_2_0_sva_2, not_26_nl);
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      input_sva <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_39 ) begin
      input_sva <= input_rsci_idat;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      mac_for_i_2_0_sva <= 3'b000;
    end
    else if ( ~ (fsm_output[2]) ) begin
      mac_for_i_2_0_sva <= MUX_v_3_2_2(3'b000, mac_for_i_2_0_sva_2, not_27_nl);
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_output_triosy_obj_ld <= 1'b0;
      reg_fir_output_triosy_obj_ld_cse <= 1'b0;
      mac_for_mac_for_nor_itm <= 1'b0;
      mac_for_if_mux_itm <= 32'b00000000000000000000000000000000;
      mac_for_if_mux_1_itm <= 2'b00;
    end
    else begin
      iir_output_triosy_obj_ld <= fsm_output[3];
      reg_fir_output_triosy_obj_ld_cse <= or_tmp_32;
      mac_for_mac_for_nor_itm <= ~((readslicef_4_1_3(mac_for_acc_nl)) | (readslicef_4_1_3(mac_1_for_acc_nl))
          | (readslicef_4_1_3(mac_2_for_acc_nl)));
      mac_for_if_mux_itm <= MUX_v_32_5_2(input_sva, reg_iir_input_delay_lane_0_cse,
          reg_iir_input_delay_lane_1_cse, reg_iir_input_delay_lane_2_cse, reg_iir_input_delay_lane_3_cse,
          mac_for_i_2_0_sva);
      mac_for_if_mux_1_itm <= MUX_v_2_5_2(2'b01, 2'b10, 2'b11, 2'b10, 2'b01, mac_for_i_2_0_sva);
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_input_delay_lane_3_sva_1 <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_39 ) begin
      iir_input_delay_lane_3_sva_1 <= reg_iir_input_delay_lane_2_cse;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_input_delay_lane_2_sva_1 <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_39 ) begin
      iir_input_delay_lane_2_sva_1 <= reg_iir_input_delay_lane_1_cse;
    end
  end
  always @(posedge clk) begin
    if ( ~ rst_n ) begin
      iir_input_delay_lane_1_sva_1 <= 32'b00000000000000000000000000000000;
    end
    else if ( ~ or_tmp_39 ) begin
      iir_input_delay_lane_1_sva_1 <= reg_iir_input_delay_lane_0_cse;
    end
  end
  assign not_25_nl = ~ or_tmp_22;
  assign mac_1_result_not_1_nl = ~ (fsm_output[0]);
  assign not_26_nl = ~ or_tmp_22;
  assign not_27_nl = ~ or_tmp_22;
  assign nl_mac_for_acc_nl = conv_u2s_3_4(mac_for_i_2_0_sva_2) + 4'b1011;
  assign mac_for_acc_nl = nl_mac_for_acc_nl[3:0];
  assign nl_mac_1_for_acc_nl = conv_u2s_3_4(mac_1_for_i_2_0_sva_2) + 4'b1011;
  assign mac_1_for_acc_nl = nl_mac_1_for_acc_nl[3:0];
  assign nl_mac_2_for_acc_nl = conv_u2s_3_4(mac_2_for_i_2_0_sva_2) + 4'b1011;
  assign mac_2_for_acc_nl = nl_mac_2_for_acc_nl[3:0];
  assign mac_2_for_if_mux_3_nl = MUX_v_32_2_2(mac_2_result_sva, mac_result_sva, fsm_output[2]);
  assign mac_2_for_if_mux_5_nl = MUX_v_32_5_2(reg_iir_output_rsci_idat_cse, iir_output_delay_lane_1_sva,
      iir_output_delay_lane_2_sva, iir_output_delay_lane_3_sva, iir_output_delay_lane_4_sva,
      mac_2_for_i_2_0_sva);
  assign mac_2_for_if_or_2_nl = (~((~((mac_2_for_i_2_0_sva!=3'b000))) | ((mac_2_for_i_2_0_sva==3'b011))
      | ((mac_2_for_i_2_0_sva==3'b100)))) | mac_2_for_if_and_3_itm;
  assign nl_mac_2_for_if_mul_1_nl = $signed(mac_2_for_if_mux_5_nl) * $signed(({mac_2_for_if_and_3_itm
      , mac_2_for_if_or_2_nl}));
  assign mac_2_for_if_mul_1_nl = nl_mac_2_for_if_mul_1_nl[31:0];
  assign mac_2_for_if_mux_4_nl = MUX_v_32_2_2(mac_2_for_if_mul_1_nl, z_out_2, fsm_output[2]);
  assign nl_z_out = mac_2_for_if_mux_3_nl + mac_2_for_if_mux_4_nl;
  assign z_out = nl_z_out[31:0];
  assign mac_1_for_if_mux_5_nl = MUX_v_32_2_2(z_out_2, mac_2_result_sva, fsm_output[3]);
  assign nl_z_out_1 = mac_1_result_sva + mac_1_for_if_mux_5_nl;
  assign z_out_1 = nl_z_out_1[31:0];
  assign mac_1_for_if_or_2_nl = mac_1_for_if_mac_1_for_if_nor_1_cse | mac_1_for_if_and_1_cse;
  assign mac_1_for_if_or_3_nl = mac_1_for_if_and_2_cse | mac_1_for_if_and_3_cse;
  assign mac_1_for_if_mux1h_1_nl = MUX1HOT_v_2_3_2(2'b01, 2'b10, mac_for_if_mux_1_itm,
      {mac_1_for_if_or_2_nl , mac_1_for_if_or_3_nl , (fsm_output[2])});
  assign mac_1_for_if_mac_1_for_if_or_1_nl = MUX_v_2_2_2(mac_1_for_if_mux1h_1_nl,
      2'b11, mac_1_for_if_and_4_cse);
  assign mac_1_for_if_mac_1_for_if_mux1h_1_nl = MUX1HOT_v_32_6_2(input_sva, reg_iir_input_delay_lane_0_cse,
      reg_iir_input_delay_lane_1_cse, reg_iir_input_delay_lane_2_cse, reg_iir_input_delay_lane_3_cse,
      mac_for_if_mux_itm, {mac_1_for_if_mac_1_for_if_nor_1_cse , mac_1_for_if_and_2_cse
      , mac_1_for_if_and_4_cse , mac_1_for_if_and_3_cse , mac_1_for_if_and_1_cse
      , (fsm_output[2])});
  assign nl_z_out_2 = mac_1_for_if_mac_1_for_if_or_1_nl * mac_1_for_if_mac_1_for_if_mux1h_1_nl;
  assign z_out_2 = nl_z_out_2[31:0];

  function automatic [1:0] MUX1HOT_v_2_3_2;
    input [1:0] input_2;
    input [1:0] input_1;
    input [1:0] input_0;
    input [2:0] sel;
    reg [1:0] result;
  begin
    result = input_0 & {2{sel[0]}};
    result = result | (input_1 & {2{sel[1]}});
    result = result | (input_2 & {2{sel[2]}});
    MUX1HOT_v_2_3_2 = result;
  end
  endfunction


  function automatic [31:0] MUX1HOT_v_32_6_2;
    input [31:0] input_5;
    input [31:0] input_4;
    input [31:0] input_3;
    input [31:0] input_2;
    input [31:0] input_1;
    input [31:0] input_0;
    input [5:0] sel;
    reg [31:0] result;
  begin
    result = input_0 & {32{sel[0]}};
    result = result | (input_1 & {32{sel[1]}});
    result = result | (input_2 & {32{sel[2]}});
    result = result | (input_3 & {32{sel[3]}});
    result = result | (input_4 & {32{sel[4]}});
    result = result | (input_5 & {32{sel[5]}});
    MUX1HOT_v_32_6_2 = result;
  end
  endfunction


  function automatic [1:0] MUX_v_2_2_2;
    input [1:0] input_0;
    input [1:0] input_1;
    input  sel;
    reg [1:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_2_2_2 = result;
  end
  endfunction


  function automatic [1:0] MUX_v_2_5_2;
    input [1:0] input_0;
    input [1:0] input_1;
    input [1:0] input_2;
    input [1:0] input_3;
    input [1:0] input_4;
    input [2:0] sel;
    reg [1:0] result;
  begin
    case (sel)
      3'b000 : begin
        result = input_0;
      end
      3'b001 : begin
        result = input_1;
      end
      3'b010 : begin
        result = input_2;
      end
      3'b011 : begin
        result = input_3;
      end
      default : begin
        result = input_4;
      end
    endcase
    MUX_v_2_5_2 = result;
  end
  endfunction


  function automatic [31:0] MUX_v_32_2_2;
    input [31:0] input_0;
    input [31:0] input_1;
    input  sel;
    reg [31:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_32_2_2 = result;
  end
  endfunction


  function automatic [31:0] MUX_v_32_5_2;
    input [31:0] input_0;
    input [31:0] input_1;
    input [31:0] input_2;
    input [31:0] input_3;
    input [31:0] input_4;
    input [2:0] sel;
    reg [31:0] result;
  begin
    case (sel)
      3'b000 : begin
        result = input_0;
      end
      3'b001 : begin
        result = input_1;
      end
      3'b010 : begin
        result = input_2;
      end
      3'b011 : begin
        result = input_3;
      end
      default : begin
        result = input_4;
      end
    endcase
    MUX_v_32_5_2 = result;
  end
  endfunction


  function automatic [2:0] MUX_v_3_2_2;
    input [2:0] input_0;
    input [2:0] input_1;
    input  sel;
    reg [2:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_3_2_2 = result;
  end
  endfunction


  function automatic [0:0] readslicef_4_1_3;
    input [3:0] vector;
    reg [3:0] tmp;
  begin
    tmp = vector >> 3;
    readslicef_4_1_3 = tmp[0:0];
  end
  endfunction


  function automatic [3:0] conv_u2s_3_4 ;
    input [2:0]  vector ;
  begin
    conv_u2s_3_4 =  {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    filter
// ------------------------------------------------------------------


module filter (
  clk, rst_n, input_rsc_dat, input_triosy_lz, fir_output_rsc_dat, fir_output_triosy_lz,
      iir_output_rsc_dat, iir_output_triosy_lz
);
  input clk;
  input rst_n;
  input [31:0] input_rsc_dat;
  output input_triosy_lz;
  output [31:0] fir_output_rsc_dat;
  output fir_output_triosy_lz;
  output [31:0] iir_output_rsc_dat;
  output iir_output_triosy_lz;



  // Interconnect Declarations for Component Instantiations 
  filter_core filter_core_inst (
      .clk(clk),
      .rst_n(rst_n),
      .input_rsc_dat(input_rsc_dat),
      .input_triosy_lz(input_triosy_lz),
      .fir_output_rsc_dat(fir_output_rsc_dat),
      .fir_output_triosy_lz(fir_output_triosy_lz),
      .iir_output_rsc_dat(iir_output_rsc_dat),
      .iir_output_triosy_lz(iir_output_triosy_lz)
    );
endmodule



